### ISSUE TITLE
Unknown item mapping Item Unknown (832:0)

### ISSUE THREAD

**Issue by RealTriassic** [PowerNukkit/PowerNukkit#1021]
# 🐞 I found a bug

2021-03-27 17:43:19.122 [main] ERROR - An error occurred whilst handling PlayerActionPacket for PowerNukkitUser
java.lang.IllegalArgumentException: Unknown item mapping Item Unknown (832:0)x1
    at cn.nukkit.item.RuntimeItemMapping.getNetworkFullId(RuntimeItemMapping.java:81) ~[server.jar:?]
    at cn.nukkit.utils.BinaryStream.putSlot(BinaryStream.java:475) ~[server.jar:?]
    at cn.nukkit.network.protocol.InventorySlotPacket.encode(InventorySlotPacket.java:35) ~[server.jar:?]
    at cn.nukkit.network.protocol.DataPacket.tryEncode(DataPacket.java:29) ~[server.jar:?]
    at cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:219) ~[server.jar:?]
    at cn.nukkit.Player.dataPacket(Player.java:1160) ~[server.jar:?]
    at cn.nukkit.inventory.PlayerInventory.sendSlot(PlayerInventory.java:463) ~[server.jar:?]
    at cn.nukkit.inventory.PlayerInventory.sendSlot(PlayerInventory.java:446) ~[server.jar:?]
    at cn.nukkit.inventory.PlayerInventory.sendHeldItem(PlayerInventory.java:159) ~[server.jar:?]
    at cn.nukkit.Player.handleDataPacket(Player.java:2669) ~[server.jar:?]
    at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
    at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:122) [server.jar:?]
    at cn.nukkit.network.Network.processInterfaces(Network.java:169) [server.jar:?]
    at cn.nukkit.Server.tick(Server.java:1364) [server.jar:?]
    at cn.nukkit.Server.tickProcessor(Server.java:1140) [server.jar:?]
    at cn.nukkit.Server.start(Server.java:1100) [server.jar:?]
    at cn.nukkit.Server.<init>(Server.java:772) [server.jar:?]
    at cn.nukkit.Nukkit.main(Nukkit.java:194) [server.jar:?]

### 📋 Debug information
* PowerNukkit version: This server is running Nukkit 1.4.0.0-PN-SNAPSHOT (git-b7f4ffa) 「PowerNukkit」 implementing API version 1.0.12 for Minecraft: BE v1.16.210 (protocol version 428)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by joserobjr** [comment]
Thank you for the report. Which item did you try to hold?

**Comment by RealTriassic** [comment]
I sadly don't know, i just saw this in console..
