### ISSUE TITLE
Issue with unloading a world that apparently is already closed and "has no providers".

### ISSUE THREAD

**Issue by RealTriassic** [PowerNukkit/PowerNukkit#1025]
# 🐞 I found a bug
2021-03-27 16:26:53.338 [main] INFO  - Unloading level "hi jose i hope you see this..."
2021-03-27 16:26:53.367 [main] ERROR - nukkit.level.tickError
cn.nukkit.utils.LevelException: The level "Hi again jose.." is already closed (have no providers)
    at cn.nukkit.level.Level.requireProvider(Level.java:480) ~[server.jar:?]
    at cn.nukkit.level.Level.getChunk(Level.java:2892) ~[server.jar:?]
    at cn.nukkit.level.Level.getChunk(Level.java:2887) ~[server.jar:?]
    at cn.nukkit.level.Level.getBlock(Level.java:1706) ~[server.jar:?]
    at cn.nukkit.level.Level.getBlock(Level.java:1691) ~[server.jar:?]
    at cn.nukkit.level.Level.getBlock(Level.java:1675) ~[server.jar:?]
    at cn.nukkit.level.Position.getLevelBlockAtLayer(Position.java:140) ~[server.jar:?]
    at cn.nukkit.Player.checkBlockCollision(Player.java:1499) ~[server.jar:?]
    at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:1415) ~[server.jar:?]
    at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:236) ~[server.jar:?]
    at cn.nukkit.Player.entityBaseTick(Player.java:1963) ~[server.jar:?]
    at cn.nukkit.Player.onUpdate(Player.java:1858) ~[server.jar:?]
    at cn.nukkit.level.Level.doTick(Level.java:942) ~[server.jar:?]
    at cn.nukkit.Server.checkTickUpdates(Server.java:1293) [server.jar:?]
    at cn.nukkit.Server.tick(Server.java:1375) [server.jar:?]
    at cn.nukkit.Server.tickProcessor(Server.java:1140) [server.jar:?]
    at cn.nukkit.Server.start(Server.java:1100) [server.jar:?]
    at cn.nukkit.Server.<init>(Server.java:772) [server.jar:?]
    at cn.nukkit.Nukkit.main(Nukkit.java:194) [server.jar:?]

### 📋 Debug information
* PowerNukkit version: This server is running Nukkit 1.4.0.0-PN-SNAPSHOT (git-b7f4ffa) 「PowerNukkit」 implementing API version 1.0.12 for Minecraft: BE v1.16.210 (protocol version 428)
* Debug link: 
* Timings link (if relevant):

**Comment by RealTriassic** [comment]
Here is a debugpaste:
https://debugpaste.powernukkit.org/pastes/PN964f4d08/

**Comment by AlicanCopur** [comment]
Can confirm.
