### ISSUE TITLE
Outdated Version of Minecraft

### ISSUE THREAD

**Issue by GabeCoder** [PowerNukkit/PowerNukkit#1037]
Yes, I already said this 3 times, but I need to remind you that PowerNukkit’s version is extremely outdated and only runs 1.16.201 as a server. Right now, Bedrock Edition players are playing the latest version, 1.16.210 on their devices, and it isn’t actually easy for them to downgrade to a lower version.
I run PowerNukkit Alpha 3 on Linux.

**Comment by GabeCoder** [comment]
> Hey @GabeCoder, thank you for the report!
> 
> ⚠️ **I could not find which PowerNukkit version you are using from your message.** ⚠️
> 
> Please, run the command: `/debugpaste` it will generate a link, send us this link replying this issue.
> It's an important step to get your issue resolved.
> 
> Don't say _latest_ or _current version_, we support different versions and your latest may not be the same latest as our, and your latest will not be the same latest in the future, so please, use a fixed version.
> 
> Thank you 👍

PowerNukkit Alpha 3

**Comment by MonoAdrian23** [comment]
At first, Powernukkits latest version is for 1.16.210
And next, you must run /debugpaste in you're console

**Comment by GabeCoder** [comment]
Here is the output!
```
java.io.IOException: Server returned HTTP response code: 500 for URL: https://hastebin.com/documents
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250) ~[?:?]
	at cn.nukkit.utils.HastebinUtility.upload(HastebinUtility.java:30) ~[powernukkit-1.3.2.0-PN-ALPHA.3-CUSTOM-shaded.jar:?]
	at cn.nukkit.command.defaults.DebugPasteCommand$1.onRun(DebugPasteCommand.java:40) [powernukkit-1.3.2.0-PN-ALPHA.3-CUSTOM-shaded.jar:?]
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) [powernukkit-1.3.2.0-PN-ALPHA.3-CUSTOM-shaded.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
And yes, the last time I tried 1.16.210, it was unstable. Second time's worth it, I guess.

**Comment by MonoAdrian23** [comment]
Then you must use a unstable Version to join latest Minecraft Versions.
1.4.0.0 works great without problems

**Comment by GabeCoder** [comment]
> Then you must use a unstable Version to join latest Minecraft Versions.
> 1.4.0.0 works great without problems

I guess instability isn't always bad.
I'll give it a try.

**Comment by MonoAdrian23** [comment]
Don't forget to backup you're server
