### ISSUE TITLE
Slowness Arrow

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1048]
# 🐞 I found a bug

```java
[36m10:47:03[m [[m[1;31mERROR[m[m] Could not create an entity of type SlownessArrow with 0 args 
java.lang.IllegalArgumentException: Could not create an entity of type SlownessArrow 
at cn.nukkit.entity.Entity.createEntity(Entity.java:913) [powernukkit-stable.jar:?] 
at cn.nukkit.level.format.generic.BaseFullChunk.initChunk(BaseFullChunk.java:149) [powernukkit-stable.jar:?] 
at cn.nukkit.level.Level.forceLoadChunk(Level.java:3254) [powernukkit-stable.jar:?] 
at cn.nukkit.level.Level.getChunk(Level.java:2894) [powernukkit-stable.jar:?] 
at cn.nukkit.level.Level.populateChunk(Level.java:3473) [powernukkit-stable.jar:?] 
at cn.nukkit.level.Level.populateChunk(Level.java:3464) [powernukkit-stable.jar:?] 
at cn.nukkit.Player.sendNextChunk(Player.java:896) [powernukkit-stable.jar:?] 
at cn.nukkit.Player.checkNetwork(Player.java:2039) [powernukkit-stable.jar:?] 
at cn.nukkit.Server.tick(Server.java:1378) [powernukkit-stable.jar:?] 
at cn.nukkit.Server.tickProcessor(Server.java:1140) [powernukkit-stable.jar:?] 
at cn.nukkit.Server.start(Server.java:1100) [powernukkit-stable.jar:?] 
at cn.nukkit.Server.<init>(Server.java:772) [powernukkit-stable.jar:?] 
at cn.nukkit.Nukkit.main(Nukkit.java:194) [powernukkit-stable.jar:?]
```
### ▶ Steps to Reproduce

1. Don't know how to reproduce
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-3bb9763)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by Jl1mbo** [comment]
After what actions did this error appear?

**Comment by MonoAdrian23** [comment]
I can't reproduce it.
It happens randomly for me.
But I think it's a problem from a plugin by me.

**Comment by MonoAdrian23** [comment]
MobPlugin spawn a stray and this error occours

**Comment by GoodLucky777** [comment]
I think it is because Nukkit arrow is not compatible with PowerNukkit after the arrow update

**Comment by joserobjr** [comment]
The `SlownessArrow` source: https://github.com/Nukkit-coders/MobPlugin/blob/master/src/main/java/nukkitcoders/mobplugin/entities/projectile/EntitySlownessArrow.java

**Comment by joserobjr** [comment]
Apparently it's a bug with the MobPlugin, this message will not be logged to Cloudburst Nukkit because the entities are being silently discarded, we a warning log when this happens.

The problem is that the class only declares this constructor:
```java
public EntitySlownessArrow(FullChunk chunk, CompoundTag nbt, Entity shootingEntity)
```
This is used when the entity is created for the first time, the plugin creates it giving the shootingEntity as argument. But when you unload the chunk and load it back, the server have to reconstruct the entity with a new instance, but this time we don't have the original shootingEntity that was used to build it for the first time, this is why the `BaseFullChunk.initChunk` creates all entities without custom args and it is expected that all entities have a constructor that accepts only `(FullChunk chunk, CompoundTag nbt), the same as it is done here: https://github.com/CloudburstMC/Nukkit/blob/master/src/main/java/cn/nukkit/entity/projectile/EntityArrow.java#L57-L67

You can ignore this warning in this case as that arrows might not be collectable, so it shouldn't harm if it can't load from the save.

**Comment by joserobjr** [comment]
I reduced the level of the message, should appear only when the debug mode is enabled.
