### ISSUE TITLE
Small incompatibility with TheEnd plugin by Wode.

### ISSUE THREAD

**Issue by RealTriassic** [PowerNukkit/PowerNukkit#1052]
# 🔌 Plugin compatibility issue

### ▶ Steps to Reproduce

1. Respawn the Ender Dragon using End Crystals.
2. Wait for an apparent explosion.
3. See Error.

### ✔ Expected Behavior

No errors occur.

### ❌ Actual Behavior

```java
java.lang.NullPointerException: null
at cn.nukkit.level.Explosion.explodeB(Explosion.java:306) ~[server.jar:?]
at cn.wode490390.nukkit.theend.scheduler.EnderDragonResummonAnimationSubTask$EnderDragonRespawnAnimation$3.tick(EnderDragonResummonAnimationSubTask.java:140) ~[?:?]
at cn.wode490390.nukkit.theend.scheduler.EnderDragonResummonAnimationSubTask.onRun(EnderDragonResummonAnimationSubTask.java:44) ~[?:?]
at cn.nukkit.scheduler.Task.run(Task.java:52) ~[server.jar:?]
at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:100) [server.jar:?]
at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:298) [server.jar:?]
at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:279) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1372) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:1140) [server.jar:?]
at cn.nukkit.Server.start(Server.java:1100) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:772) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:194) [server.jar:?]
```

### 📋 Debug information

* PowerNukkit version: This server is running Nukkit 1.4.0.0-PN-SNAPSHOT (git-3bb9763) 「PowerNukkit」 implementing API version 1.0.12 for Minecraft: BE v1.16.220 (protocol version 431)

**Comment by GoodLucky777** [comment]
I open the pull request for that problem (#988)
