### ISSUE TITLE
Plotsquared

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1069]
# 🔌 Plugin compatibility issue
 There is a little Problem with Plotsquared Bucket Empty Event

```java

[36m19:43:36[m [[m[1;31mERROR[m[m] Das Event "cn.nukkit.event.player.PlayerBucketEmptyEvent" konnte nicht zu "PlotSquared v19.12.10-b4c257b-783": null in Zeile com.plotsquared.nukkit.listeners.PlayerEvents weitergegeben werden

cn.nukkit.utils.EventException: null

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:35) ~[powernukkit-stable.jar:?]

at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[powernukkit-stable.jar:?]

at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:570) [powernukkit-stable.jar:?]

at cn.nukkit.block.BlockCauldron.onActivate(BlockCauldron.java:134) [powernukkit-stable.jar:?]

at cn.nukkit.level.Level.useItemOn(Level.java:2440) [powernukkit-stable.jar:?]

at cn.nukkit.level.Level.useItemOn(Level.java:2397) [powernukkit-stable.jar:?]

at cn.nukkit.Player.handleDataPacket(Player.java:3624) [powernukkit-stable.jar:?]

at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:124) [powernukkit-stable.jar:?]

at cn.nukkit.network.Network.processInterfaces(Network.java:169) [powernukkit-stable.jar:?]

at cn.nukkit.Server.tick(Server.java:1364) [powernukkit-stable.jar:?]

at cn.nukkit.Server.tickProcessor(Server.java:1140) [powernukkit-stable.jar:?]

at cn.nukkit.Server.start(Server.java:1100) [powernukkit-stable.jar:?]

at cn.nukkit.Server.<init>(Server.java:772) [powernukkit-stable.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:194) [powernukkit-stable.jar:?]

Caused by: java.lang.NullPointerException

[36m19:47:16[m [[m[1;31mERROR[m[m] Das Event "cn.nukkit.event.player.PlayerBucketEmptyEvent" konnte nicht zu "PlotSquared v19.12.10-b4c257b-783": null in Zeile com.plotsquared.nukkit.listeners.PlayerEvents weitergegeben werden

cn.nukkit.utils.EventException: null

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:35) ~[powernukkit-stable.jar:?]

at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[powernukkit-stable.jar:?]

at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:570) [powernukkit-stable.jar:?]

at cn.nukkit.block.BlockCauldron.onActivate(BlockCauldron.java:134) [powernukkit-stable.jar:?]

at cn.nukkit.level.Level.useItemOn(Level.java:2440) [powernukkit-stable.jar:?]

at cn.nukkit.level.Level.useItemOn(Level.java:2397) [powernukkit-stable.jar:?]

at cn.nukkit.Player.handleDataPacket(Player.java:3624) [powernukkit-stable.jar:?]

at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:124) [powernukkit-stable.jar:?]

at cn.nukkit.network.Network.processInterfaces(Network.java:169) [powernukkit-stable.jar:?]

at cn.nukkit.Server.tick(Server.java:1364) [powernukkit-stable.jar:?]

at cn.nukkit.Server.tickProcessor(Server.java:1140) [powernukkit-stable.jar:?]

at cn.nukkit.Server.start(Server.java:1100) [powernukkit-stable.jar:?]

at cn.nukkit.Server.<init>(Server.java:772) [powernukkit-stable.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:194) [powernukkit-stable.jar:?]

Caused by: java.lang.NullPointerException

[36m19:47:18[m [[m[1;31mERROR[m[m] Das Event "cn.nukkit.event.player.PlayerBucketEmptyEvent" konnte nicht zu "PlotSquared v19.12.10-b4c257b-783": null in Zeile com.plotsquared.nukkit.listeners.PlayerEvents weitergegeben werden

cn.nukkit.utils.EventException: null

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:35) ~[powernukkit-stable.jar:?]

at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[powernukkit-stable.jar:?]

at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:570) [powernukkit-stable.jar:?]

at cn.nukkit.block.BlockCauldron.onActivate(BlockCauldron.java:134) [powernukkit-stable.jar:?]

at cn.nukkit.level.Level.useItemOn(Level.java:2440) [powernukkit-stable.jar:?]

at cn.nukkit.level.Level.useItemOn(Level.java:2397) [powernukkit-stable.jar:?]

at cn.nukkit.Player.handleDataPacket(Player.java:3624) [powernukkit-stable.jar:?]

at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:124) [powernukkit-stable.jar:?]

at cn.nukkit.network.Network.processInterfaces(Network.java:169) [powernukkit-stable.jar:?]

at cn.nukkit.Server.tick(Server.java:1364) [powernukkit-stable.jar:?]

at cn.nukkit.Server.tickProcessor(Server.java:1140) [powernukkit-stable.jar:?]

at cn.nukkit.Server.start(Server.java:1100) [powernukkit-stable.jar:?]

at cn.nukkit.Server.<init>(Server.java:772) [powernukkit-stable.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:194) [powernukkit-stable.jar:?]

Caused by: java.lang.NullPointerException

[36m19:47:56[m [[m[1;31mERROR[m[m] Das Event "cn.nukkit.event.player.PlayerBucketEmptyEvent" konnte nicht zu "PlotSquared v19.12.10-b4c257b-783": null in Zeile com.plotsquared.nukkit.listeners.PlayerEvents weitergegeben werden

cn.nukkit.utils.EventException: null

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:35) ~[powernukkit-stable.jar:?]

at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[powernukkit-stable.jar:?]

at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:570) [powernukkit-stable.jar:?]

at cn.nukkit.block.BlockCauldron.onActivate(BlockCauldron.java:134) [powernukkit-stable.jar:?]

at cn.nukkit.level.Level.useItemOn(Level.java:2440) [powernukkit-stable.jar:?]

at cn.nukkit.level.Level.useItemOn(Level.java:2397) [powernukkit-stable.jar:?]

at cn.nukkit.Player.handleDataPacket(Player.java:3624) [powernukkit-stable.jar:?]

at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:124) [powernukkit-stable.jar:?]

at cn.nukkit.network.Network.processInterfaces(Network.java:169) [powernukkit-stable.jar:?]

at cn.nukkit.Server.tick(Server.java:1364) [powernukkit-stable.jar:?]

at cn.nukkit.Server.tickProcessor(Server.java:1140) [powernukkit-stable.jar:?]

at cn.nukkit.Server.start(Server.java:1100) [powernukkit-stable.jar:?]

at cn.nukkit.Server.<init>(Server.java:772) [powernukkit-stable.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:194) [powernukkit-stable.jar:?]

Caused by: java.lang.NullPointerException

[36m19:48:03[m [[m[34mINFO [m[m]
```

### ▶ Steps to Reproduce

1. Try to empty a Bucket on a Plot
2. See this Error
3. I think this is a compatibilty issue

### 📋 Debug information

* PowerNukkit version: (git-0198a40)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by joserobjr** [comment]
Hi! Thank you for the report. After analyzing I found out that it's a bug in the plugin. The `PlayerBucketFillEvent` and `PlayerBucketEmptyEvent` may have `null` value for the `getBlockFace()` property. This happens when the bucket is filled or emptied at cauldrons. This behavior exists in Nukkit since 1e5242a38ac7e7a4ac2f9d0b6a075a4b87639a56 (2017-05-01)

To stop that from happening, `com.plotsquared.nukkit.listeners.PlayerEvents.onBucketEmpty()` (line 1319) needs to be adjusted to check for null before calling `block.getSide(event.getBlockFace())`

Example:
```java
Block block = event.getBlockClicked();
Block b = event.getBlockFace() != null? block.getSide(event.getBlockFace()) : block;
```
