### ISSUE TITLE
BlockItemFrame.recalculateBoundingBox NullPointerException Error

### ISSUE THREAD

**Issue by GoodLucky777** [PowerNukkit/PowerNukkit#1079]
# 🐞 I found a bug

### ▶ Steps to Reproduce

Unknown

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT (e1a2217efc8a5e28df830e28033c5a74eb9255b0)
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

```
[main] ERROR - nukkit.level.tickError
java.lang.NullPointerException: null
	at cn.nukkit.block.BlockItemFrame.recalculateBoundingBox(BlockItemFrame.java:240) ~[powernukkit.jar:?]
	at cn.nukkit.block.Block.getBoundingBox(Block.java:1590) ~[powernukkit.jar:?]
	at cn.nukkit.block.Block.recalculateCollisionBoundingBox(Block.java:1632) ~[powernukkit.jar:?]
	at cn.nukkit.block.Block.getCollisionBoundingBox(Block.java:1594) ~[powernukkit.jar:?]
	at cn.nukkit.block.Block.collidesWithBB(Block.java:1581) ~[powernukkit.jar:?]
	at cn.nukkit.level.Level.doTick(Level.java:942) ~[powernukkit.jar:?]
	at cn.nukkit.Server.checkTickUpdates(Server.java:1293) [powernukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1375) [powernukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1140) [powernukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1100) [powernukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:772) [powernukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:194) [powernukkit.jar:?]
```

### 💬 Anything else we should know?

-

**Comment by joserobjr** [comment]
Thank you for the report!
