### ISSUE TITLE
IllegalArgumentException: Unknown item mapping Item

### ISSUE THREAD

**Issue by GoodLucky777** [PowerNukkit/PowerNukkit#1084]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Update PowerNukkit(e1a2217efc8a5e28df830e28033c5a74eb9255b0) to PowerNukkit(bb574badc65b53094e709e98aa31113c85dcad61)
2. See error after I open the inventory

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-SNAPSHOT (bb574badc65b53094e709e98aa31113c85dcad61)
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

```
[main] ERROR - An error occurred whilst handling InventoryTransactionPacket for SomePlayer
java.lang.IllegalArgumentException: Unknown item mapping Item Spawn EntityEgg (383:92)x1 tags:0x0A0000030A00526570616972436F7374000000000A0700646973706C61790804004E616D650C00C2A761ED9DACEAB780ED859C0000
	at cn.nukkit.item.RuntimeItemMapping.getNetworkFullId(RuntimeItemMapping.java:82) ~[powernukkit.jar:?]
	at cn.nukkit.utils.BinaryStream.putSlot(BinaryStream.java:495) ~[powernukkit.jar:?]
	at cn.nukkit.utils.BinaryStream.putSlot(BinaryStream.java:485) ~[powernukkit.jar:?]
	at cn.nukkit.network.protocol.InventoryContentPacket.encode(InventoryContentPacket.java:45) ~[powernukkit.jar:?]
	at cn.nukkit.network.protocol.DataPacket.tryEncode(DataPacket.java:29) ~[powernukkit.jar:?]
	at cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:221) ~[powernukkit.jar:?]
	at cn.nukkit.Player.dataPacket(Player.java:1164) ~[powernukkit.jar:?]
	at cn.nukkit.inventory.BaseInventory.sendContents(BaseInventory.java:498) ~[powernukkit.jar:?]
	at cn.nukkit.inventory.BaseInventory.sendContents(BaseInventory.java:480) ~[powernukkit.jar:?]
	at cn.nukkit.inventory.PlayerEnderChestInventory.onOpen(PlayerEnderChestInventory.java:46) ~[powernukkit.jar:?]
	at cn.nukkit.inventory.BaseInventory.open(BaseInventory.java:432) ~[powernukkit.jar:?]
	at cn.nukkit.Player.addWindow(Player.java:5319) ~[powernukkit.jar:?]
	at cn.nukkit.Player.addWindow(Player.java:5300) ~[powernukkit.jar:?]
	at cn.nukkit.Player.addWindow(Player.java:5296) ~[powernukkit.jar:?]
	at cn.nukkit.Player.addWindow(Player.java:5292) ~[powernukkit.jar:?]
	at cn.nukkit.block.BlockEnderChest.onActivate(BlockEnderChest.java:159) ~[powernukkit.jar:?]
	at cn.nukkit.level.Level.useItemOn(Level.java:2440) ~[powernukkit.jar:?]
	at cn.nukkit.level.Level.useItemOn(Level.java:2397) ~[powernukkit.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:3635) ~[powernukkit.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:124) [powernukkit.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:169) [powernukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1364) [powernukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1140) [powernukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1100) [powernukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:772) [powernukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:194) [powernukkit.jar:?]
```

### 💬 Anything else we should know?

-

**Comment by joserobjr** [comment]
Thank you for reporting!
