### ISSUE TITLE
Raknet Issue

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1098]
# 🐞 I found a bug

[36m12:49:50[m [[m[31mWARN [m[m] A task raised an exception. Task: com.nukkitx.network.raknet.RakNetServer$$Lambda$875/178497375@56b77261

java.lang.NullPointerException: null

at com.nukkitx.network.raknet.RakNetSession.initHeapWeights(RakNetSession.java:180) ~[powernukkit-stable.jar:?]

at com.nukkitx.network.raknet.RakNetSession.deinitialize(RakNetSession.java:146) ~[powernukkit-stable.jar:?]

at com.nukkitx.network.raknet.RakNetSession.close0(RakNetSession.java:594) ~[powernukkit-stable.jar:?]

at com.nukkitx.network.raknet.RakNetSession.close(RakNetSession.java:581) ~[powernukkit-stable.jar:?]

at com.nukkitx.network.raknet.RakNetSession.tick(RakNetSession.java:422) ~[powernukkit-stable.jar:?]

at com.nukkitx.network.raknet.RakNetSession.onTick(RakNetSession.java:417) ~[powernukkit-stable.jar:?]

at com.nukkitx.network.raknet.RakNetServer.lambda$onTick$1(RakNetServer.java:129) ~[powernukkit-stable.jar:?]

at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [powernukkit-stable.jar:?]

at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [powernukkit-stable.jar:?]

at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [powernukkit-stable.jar:?]

at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [powernukkit-stable.jar:?]

at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [powernukkit-stable.jar:?]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

### ▶ Steps to Reproduce

1. I dont know why this happens
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-2d28005)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
It happens since i have updated Powernukkit with all latest fixes

**Comment by joserobjr** [comment]
How frequent does this happens?

**Comment by MonoAdrian23** [comment]
Its really rare
But i dont know why this happens. 
I check this out
