### ISSUE TITLE
Since PN 1.17 it happens. 

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1124]
# 🐞 I found a bug

```java
[[m[1;31mERROR[m[m] Das Event "cn.nukkit.event.block.BlockBreakEvent" konnte nicht zu "JobSystem v1.0.0": null in Zeile de.buddelbubi.events.Events weitergegeben werden
cn.nukkit.utils.EventException: null
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:35) ~[powernukkit-stable.jar:?]
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[powernukkit-stable.jar:?]
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:570) [powernukkit-stable.jar:?]
at cn.nukkit.level.Level.useBreakOn(Level.java:2263) [powernukkit-stable.jar:?]
at cn.nukkit.level.Level.useBreakOn(Level.java:2180) [powernukkit-stable.jar:?]
at cn.nukkit.level.Level.useBreakOn(Level.java:2173) [powernukkit-stable.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:3695) [powernukkit-stable.jar:?]
at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:122) [powernukkit-stable.jar:?]
at cn.nukkit.network.Network.processInterfaces(Network.java:169) [powernukkit-stable.jar:?]
at cn.nukkit.Server.tick(Server.java:1365) [powernukkit-stable.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:1141) [powernukkit-stable.jar:?]
at cn.nukkit.Server.start(Server.java:1101) [powernukkit-stable.jar:?]
at cn.nukkit.Server.<init>(Server.java:773) [powernukkit-stable.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:199) [powernukkit-stable.jar:?]
Caused by: java.lang.NullPointerException
at de.buddelbubi.events.Events.on(Events.java:56) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:30) ~[powernukkit-stable.jar:?]
```

It happens when i try to break blocks

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-97c64ce)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by Jl1mbo** [comment]
see de.buddelbubi.events.Events.on(Events.java:56)

**Comment by joserobjr** [comment]
Is this plugin public? Where can I get it?
JobSystem v1.0.0

**Comment by MonoAdrian23** [comment]
I have send you at discord

**Comment by joserobjr** [comment]
After further investigations, it was discovered that the exception was caused by a plugin issue and that it also happened before the MC 1.17 update.

The fix details were sent to @MonoAdrian23 at discord.

Thank you for the report anyway 👍

**Comment by MonoAdrian23** [comment]
Thank you very much Jose
