### ISSUE TITLE
Raknet Spams Errors on Startup

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1176]
# 🐞 I found a bug
 On startup, raknet spamms this error more then 2000 Times and kills the server.
This error doenst stop. 
Tested without Plugins. 

[36m09:54:21[m [[m[1;31mERROR[m[m] An exception occurred in RakNet (Server)

io.netty.channel.unix.Errors$NativeIoException: sendToAddress(..) failed: Invalid argument

### ▶ Steps to Reproduce

1. Start youre Powernukkit 1.5.0.0 or 1.5.0.1 Server
2. See this
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-32f0488)
* Debug link: https://debugpaste.powernukkit.org/pastes/PN43037d98
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
```
java.lang.IllegalArgumentException: blockData: Negative value is not allowed: -1
	at cn.nukkit.utils.Validation.checkPositive(Validation.java:75)
	at cn.nukkit.blockstate.BlockState.of(BlockState.java:107)
	at cn.nukkit.level.Level.setBlockAtLayer(Level.java:2790)
	at cn.nukkit.level.Level.setBlockAt(Level.java:2783)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:100)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:62)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:62)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:80)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:62)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:80)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:80)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:80)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:62)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:86)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:86)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:62)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:86)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:86)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:80)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:80)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:62)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:80)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:62)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:83)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:60)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.flowIntoBlock(LiquidUpdater.java:101)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:62)
	at cn.wode490390.nukkit.nbpop.block.LiquidUpdater.lavaSpread(LiquidUpdater.java:10)
	at cn.wode490390.nukkit.nbpop.structure.NetherBridgePieces$CastleEntrance.postProcess(NetherBridgePieces.java:799)
	at cn.wode490390.nukkit.nbpop.structure.StructureStart.lambda$postProcess$0(StructureStart.java:42)
	at java.util.ArrayList.removeIf(ArrayList.java:1413)
	at cn.wode490390.nukkit.nbpop.structure.StructureStart.postProcess(StructureStart.java:42)
	at cn.wode490390.nukkit.nbpop.populator.PopulatorNetherFortress.lambda$populate$0(PopulatorNetherFortress.java:59)
	at cn.wode490390.nukkit.nbpop.scheduler.CallbackableChunkGenerationTask.onRun(CallbackableChunkGenerationTask.java:60)
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:25)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by MonoAdrian23** [comment]
I think the NetherFortressPopulator isnt compatible with Powernukkit. 

(Compatibility Issue)

**Comment by MonoAdrian23** [comment]
Sorry i have posted this in a wrong issue. 
This error is for a seperate issue

**Comment by MonoAdrian23** [comment]
I close this issue because it doesnt happen anymore in 1.5.2.0
