### ISSUE TITLE
Population Task Error

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1186]
# 🐞 I found a bug
 
```java
18:02:39 FATAL Exception in asynchronous task
java.lang.NullPointerException: null
	at cn.nukkit.level.format.anvil.ChunkSection.setBlockSkyLight(ChunkSection.java:464) ~[powernukkit-stable.jar:?]
	at cn.nukkit.level.format.generic.BaseChunk.setBlockSkyLight(BaseChunk.java:306) ~[powernukkit-stable.jar:?]
	at cn.nukkit.level.format.generic.BaseFullChunk.populateSkyLight(BaseFullChunk.java:310) ~[powernukkit-stable.jar:?]
	at cn.nukkit.level.generator.task.PopulationTask.generationTask(PopulationTask.java:116) ~[powernukkit-stable.jar:?]
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:48) ~[powernukkit-stable.jar:?]
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
	at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:43) ~[powernukkit-stable.jar:?]
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:25) ~[powernukkit-stable.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
java.lang.NullPointerException
	at cn.nukkit.level.format.anvil.ChunkSection.setBlockSkyLight(ChunkSection.java:464)
	at cn.nukkit.level.format.generic.BaseChunk.setBlockSkyLight(BaseChunk.java:306)
	at cn.nukkit.level.format.generic.BaseFullChunk.populateSkyLight(BaseFullChunk.java:310)
	at cn.nukkit.level.generator.task.PopulationTask.generationTask(PopulationTask.java:116)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:48)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:43)
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:25)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-365cca6)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by whes1015** [comment]
> # 🐞 I found a bug
> 36m18:02:39�[m [�[m�[5;1;31mFATAL�[m�[m] Exception in asynchronous task
> java.lang.NullPointerException: null
> 
> at cn.nukkit.level.format.anvil.ChunkSection.setBlockSkyLight(ChunkSection.java:464) ~[powernukkit-stable.jar:?]
> 
> at cn.nukkit.level.format.generic.BaseChunk.setBlockSkyLight(BaseChunk.java:306) ~[powernukkit-stable.jar:?]
> 
> at cn.nukkit.level.format.generic.BaseFullChunk.populateSkyLight(BaseFullChunk.java:310) ~[powernukkit-stable.jar:?]
> 
> at cn.nukkit.level.generator.task.PopulationTask.generationTask(PopulationTask.java:116) ~[powernukkit-stable.jar:?]
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:48) ~[powernukkit-stable.jar:?]
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[powernukkit-stable.jar:?]
> 
> at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:43) ~[powernukkit-stable.jar:?]
> 
> at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:25) ~[powernukkit-stable.jar:?]
> 
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
> 
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
> 
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
> 
> java.lang.NullPointerException
> 
> at cn.nukkit.level.format.anvil.ChunkSection.setBlockSkyLight(ChunkSection.java:464)
> 
> at cn.nukkit.level.format.generic.BaseChunk.setBlockSkyLight(BaseChunk.java:306)
> 
> at cn.nukkit.level.format.generic.BaseFullChunk.populateSkyLight(BaseFullChunk.java:310)
> 
> at cn.nukkit.level.generator.task.PopulationTask.generationTask(PopulationTask.java:116)
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:48)
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
> 
> at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
> 
> at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:43)
> 
> at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:25)
> 
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 
> at java.lang.Thread.run(Thread.java:748)
> 
> ### 📸 Screenshots / Videos
> ### ▶ Steps to Reproduce
> 1. Run command '...'
> 2. Click on '....'
> 3. Put '....' at '...'
> 4. See error
> 
> ### ✔ Expected Behavior
> ### ❌ Actual Behavior
> ### 📋 Debug information
> * PowerNukkit version: (git-365cca6)
> * Debug link: ✍
> * Timings link (if relevant): ✍
> 
> ### 💢 Crash Dump, Stack Trace and Other Files
> ### 💬 Anything else we should know?

I have the same problem

**Comment by MonoAdrian23** [comment]
Wode Struture Plugins?

**Comment by joserobjr** [comment]
Linking https://github.com/PowerNukkit/PowerNukkit/issues/982

**Comment by joserobjr** [comment]
Thank you for the report, i' closing as dup of the other one because the other is older
