### ISSUE TITLE
nukkit.level.tickError

### ISSUE THREAD

**Issue by Mcayear** [PowerNukkit/PowerNukkit#1197]
# 🐞 I found a bug
Players cannot enter the server again after the "nukkit.level.tickError" occurs!

### 📋 Debug information
`2021-07-13 20:14:05.432 [MainThread] ERROR - nukkit.level.tickError
java.lang.NullPointerException: null
	at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:222) ~[powernukkit.jar:?]
	at cn.nukkit.Player.entityBaseTick(Player.java:1975) ~[powernukkit.jar:?]
	at cn.nukkit.Player.onUpdate(Player.java:1866) ~[powernukkit.jar:?]
	at cn.nukkit.level.Level.doTick(Level.java:947) ~[powernukkit.jar:?]
	at cn.nukkit.Server.checkTickUpdates(Server.java:1289) [powernukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1371) [powernukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1143) [powernukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1103) [powernukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:775) [powernukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:199) [powernukkit.jar:?]
2021-07-13 20:14:05.447 [MainThread] ERROR - nukkit.level.tickError
java.lang.NullPointerException: null
	at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:222) ~[powernukkit.jar:?]
	at cn.nukkit.Player.entityBaseTick(Player.java:1975) ~[powernukkit.jar:?]
	at cn.nukkit.Player.onUpdate(Player.java:1866) ~[powernukkit.jar:?]
	at cn.nukkit.level.Level.doTick(Level.java:947) ~[powernukkit.jar:?]
	at cn.nukkit.Server.checkTickUpdates(Server.java:1289) [powernukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1371) [powernukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1143) [powernukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1103) [powernukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:775) [powernukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:199) [powernukkit.jar:?]
2021-07-13 20:14:05.502 [MainThread] ERROR - nukkit.level.tickError
java.lang.NullPointerException: null
	at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:222) ~[powernukkit.jar:?]
	at cn.nukkit.Player.entityBaseTick(Player.java:1975) ~[powernukkit.jar:?]
	at cn.nukkit.Player.onUpdate(Player.java:1866) ~[powernukkit.jar:?]
	at cn.nukkit.level.Level.doTick(Level.java:947) ~[powernukkit.jar:?]
	at cn.nukkit.Server.checkTickUpdates(Server.java:1289) [powernukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1371) [powernukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1143) [powernukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1103) [powernukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:775) [powernukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:199) [powernukkit.jar:?]`
* PowerNukkit version: Nukkit 1.5.1.0-PN (git-365cca6)

### 💢 Crash Dump, Stack Trace and Other Files
https://paste.ubuntu.com/p/qNjffTd9Xj/

**Comment by Mcayear** [comment]
```2021-08-29 19:25:03.280 [main] FATAL - nukkit.server.networkError

java.lang.NullPointerException: null
	at com.nukkitx.fakeinventories.inventory.FakeInventory.onClose(FakeInventory.java:83) ~[fakeinventories-1.0.3-SNAPSHOT.jar:?]
	at cn.nukkit.inventory.BaseInventory.close(BaseInventory.java:439) ~[powernukkit.jar:?]
	at cn.nukkit.Player.removeWindow(Player.java:5428) ~[powernukkit.jar:?]
	at cn.nukkit.Player.removeWindow(Player.java:5423) ~[powernukkit.jar:?]
	at cn.nukkit.Player.removeAllWindows(Player.java:5517) ~[powernukkit.jar:?]
	at cn.nukkit.Player.close(Player.java:4332) ~[powernukkit.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:115) ~[powernukkit.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:169) [powernukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1360) [powernukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1143) [powernukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1103) [powernukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:775) [powernukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:199) [powernukkit.jar:?]```
**The server crashed when this error occurred.**

**Comment by Gabriel8579** [comment]
> ```
> 
> java.lang.NullPointerException: null
> 	at com.nukkitx.fakeinventories.inventory.FakeInventory.onClose(FakeInventory.java:83) ~[fakeinventories-1.0.3-SNAPSHOT.jar:?]
> 	at cn.nukkit.inventory.BaseInventory.close(BaseInventory.java:439) ~[powernukkit.jar:?]
> 	at cn.nukkit.Player.removeWindow(Player.java:5428) ~[powernukkit.jar:?]
> 	at cn.nukkit.Player.removeWindow(Player.java:5423) ~[powernukkit.jar:?]
> 	at cn.nukkit.Player.removeAllWindows(Player.java:5517) ~[powernukkit.jar:?]
> 	at cn.nukkit.Player.close(Player.java:4332) ~[powernukkit.jar:?]
> 	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:115) ~[powernukkit.jar:?]
> 	at cn.nukkit.network.Network.processInterfaces(Network.java:169) [powernukkit.jar:?]
> 	at cn.nukkit.Server.tick(Server.java:1360) [powernukkit.jar:?]
> 	at cn.nukkit.Server.tickProcessor(Server.java:1143) [powernukkit.jar:?]
> 	at cn.nukkit.Server.start(Server.java:1103) [powernukkit.jar:?]
> 	at cn.nukkit.Server.<init>(Server.java:775) [powernukkit.jar:?]
> 	at cn.nukkit.Nukkit.main(Nukkit.java:199) [powernukkit.jar:?]
> ```
> 
> **The server crashed when this error occurred.**

It seems to me to be a problem with fakeinventories
