### ISSUE TITLE
Really Important Issue / Raknet Issue 3

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1254]
# 🐞 I found a bug
 [36m14:48:15[m [[m[31mWARN [m[m] A task raised an exception. Task: com.nukkitx.network.raknet.RakNetServer$$Lambda$368/0x0000000840a07c40@72c53338

java.lang.NullPointerException: null

at com.nukkitx.network.raknet.RakNetSession.initHeapWeights(RakNetSession.java:180) ~[powernukkit-stable.jar:?]

at com.nukkitx.network.raknet.RakNetSession.deinitialize(RakNetSession.java:146) ~[powernukkit-stable.jar:?]

at com.nukkitx.network.raknet.RakNetSession.close0(RakNetSession.java:594) ~[powernukkit-stable.jar:?]

at com.nukkitx.network.raknet.RakNetSession.close(RakNetSession.java:581) ~[powernukkit-stable.jar:?]

at com.nukkitx.network.raknet.RakNetSession.tick(RakNetSession.java:422) ~[powernukkit-stable.jar:?]

at com.nukkitx.network.raknet.RakNetSession.onTick(RakNetSession.java:417) ~[powernukkit-stable.jar:?]

at com.nukkitx.network.raknet.RakNetServer.lambda$onTick$1(RakNetServer.java:129) ~[powernukkit-stable.jar:?]

at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [powernukkit-stable.jar:?]

at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [powernukkit-stable.jar:?]

at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [powernukkit-stable.jar:?]

at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [powernukkit-stable.jar:?]

at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [powernukkit-stable.jar:?]

at java.lang.Thread.run(Unknown Source) [?:?]

No Player can Join with this Error.
Its very important!

@joserobjr  @Gabriel8579 @LoboMetalurgico 

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-e230931)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by LoboMetalurgico** [comment]
Do you have any plugin installed?

**Comment by MonoAdrian23** [comment]
Only this one. 
https://cloudburstmc.org/threads/custom-join-and-quid.1089/

**Comment by LoboMetalurgico** [comment]
This plugin works with the join and quit of players. Possibly this is a compatibility issue between the plugin and PowerNukkit.

**Comment by MonoAdrian23** [comment]
I have removed this Plugin and now it works now.
Thanks for our help.
