### ISSUE TITLE
Random Kicks / Near Spawn Cactus

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1288]
# 🐞 I found a bug

[36m16:50:22[m [[m[34mINFO [m[m] uschiax[/87.169.206.185:52385] hat sich ausgeloggt generic

[36m16:50:22[m [[m[1;31mERROR[m[m] nukkit.level.tickError

java.lang.NullPointerException: null

at cn.nukkit.entity.EntityHumanType.attack(EntityHumanType.java:192) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.attack(Player.java:5032) ~[nukkit-stable.jar:?]

at cn.nukkit.block.BlockCactus.onEntityCollide(BlockCactus.java:111) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.checkBlockCollision(Player.java:1513) ~[nukkit-stable.jar:?]

at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:1556) ~[nukkit-stable.jar:?]

at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:236) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.entityBaseTick(Player.java:1985) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.onUpdate(Player.java:1876) ~[nukkit-stable.jar:?]

at cn.nukkit.level.Level.doTick(Level.java:954) ~[nukkit-stable.jar:?]

at cn.nukkit.Server.checkTickUpdates(Server.java:1292) [nukkit-stable.jar:?]

at cn.nukkit.Server.tick(Server.java:1374) [nukkit-stable.jar:?]

at cn.nukkit.Server.tickProcessor(Server.java:1146) [nukkit-stable.jar:?]

at cn.nukkit.Server.start(Server.java:1106) [nukkit-stable.jar:?]

at cn.nukkit.Server.<init>(Server.java:778) [nukkit-stable.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:200) [nukkit-stable.jar:?]

[36m16:50:56[m [[m[34mINFO [m[m] uschiax[/87.169.206.185:52385] hat sich ausgeloggt generic

[36m16:50:56[m [[m[1;31mERROR[m[m] nukkit.level.tickError

java.lang.NullPointerException: null

at cn.nukkit.entity.EntityHumanType.attack(EntityHumanType.java:192) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.attack(Player.java:5032) ~[nukkit-stable.jar:?]

at cn.nukkit.block.BlockCactus.onEntityCollide(BlockCactus.java:111) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.checkBlockCollision(Player.java:1513) ~[nukkit-stable.jar:?]

at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:1556) ~[nukkit-stable.jar:?]

at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:236) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.entityBaseTick(Player.java:1985) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.onUpdate(Player.java:1876) ~[nukkit-stable.jar:?]

at cn.nukkit.level.Level.doTick(Level.java:954) ~[nukkit-stable.jar:?]

at cn.nukkit.Server.checkTickUpdates(Server.java:1292) [nukkit-stable.jar:?]

at cn.nukkit.Server.tick(Server.java:1374) [nukkit-stable.jar:?]

at cn.nukkit.Server.tickProcessor(Server.java:1146) [nukkit-stable.jar:?]

at cn.nukkit.Server.start(Server.java:1106) [nukkit-stable.jar:?]

at cn.nukkit.Server.<init>(Server.java:778) [nukkit-stable.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:200) [nukkit-stable.jar:?]

[36m16:51:43[m [[m[34mINFO [m[m] uschiax[/87.169.206.185:59024] hat sich ausgeloggt generic

[36m16:51:43[m [[m[1;31mERROR[m[m] nukkit.level.tickError

java.lang.NullPointerException: null

at cn.nukkit.entity.EntityHumanType.attack(EntityHumanType.java:192) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.attack(Player.java:5032) ~[nukkit-stable.jar:?]

at cn.nukkit.block.BlockCactus.onEntityCollide(BlockCactus.java:111) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.checkBlockCollision(Player.java:1513) ~[nukkit-stable.jar:?]

at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:1556) ~[nukkit-stable.jar:?]

at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:236) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.entityBaseTick(Player.java:1985) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.onUpdate(Player.java:1876) ~[nukkit-stable.jar:?]

at cn.nukkit.level.Level.doTick(Level.java:954) ~[nukkit-stable.jar:?]

at cn.nukkit.Server.checkTickUpdates(Server.java:1292) [nukkit-stable.jar:?]

at cn.nukkit.Server.tick(Server.java:1374) [nukkit-stable.jar:?]

at cn.nukkit.Server.tickProcessor(Server.java:1146) [nukkit-stable.jar:?]

at cn.nukkit.Server.start(Server.java:1106) [nukkit-stable.jar:?]

at cn.nukkit.Server.<init>(Server.java:778) [nukkit-stable.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:200) [nukkit-stable.jar:?]

Its a very important Issue!
@joserobjr 

### ▶ Steps to Reproduce

1. It happens when a Player Spawn in a near of Cactus
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-70f88e5)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by PocketMiner92** [comment]
It happens when you have contact with a Cactus too

**Comment by PocketMiner92** [comment]
Its a Plugin Issue
It can be closed
