### ISSUE TITLE
Clicking a Player, Crashs the Player (Generic)

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1289]
# 🐞 I found a bug
 An error occurred whilst handling InventoryTransactionPacket for Viktoriafammm

java.lang.NullPointerException: null

at cn.nukkit.entity.EntityHumanType.attack(EntityHumanType.java:192) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.attack(Player.java:5032) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.handleDataPacket(Player.java:3925) ~[nukkit-stable.jar:?]

at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:129) [nukkit-stable.jar:?]

at cn.nukkit.network.Network.processInterfaces(Network.java:170) [nukkit-stable.jar:?]

at cn.nukkit.Server.tick(Server.java:1363) [nukkit-stable.jar:?]
cn.nukkit.Server.tick(Server.java:1363) [nukkit-stable.jar:?]

at cn.nukkit.Server.tickProcessor(Server.java:1146) [nukkit-stable.jar:?]

at cn.nukkit.Server.start(Server.java:1106) [nukkit-stable.jar:?]

at cn.nukkit.Server.<init>(Server.java:778) [nukkit-stable.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:200) [nukkit-stable.jar:?]

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-70f88e5)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by PocketMiner92** [comment]
Close please
Its a Plugin Issue.
Godmode by SaturnBoss
