### ISSUE TITLE
NoSpaceInName PetteriM1

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1339]
# 🔌 Plugin compatibility issue
 
### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git f9a0d68)
* Debug link: ✍
* Timings link (if relevant): ✍ 

### 💢 Crash Dump, Stack Trace and Other Files

```java
ERROR - Das Event "cn.nukkit.event.server.DataPacketReceiveEvent" konnte nicht zu "NoSpaceInName v1.1.0": null in Zeile me.petterim1.ns.NoSpaceInName weitergegeben werden
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:35) ~[nukkit-stable.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[nukkit-stable.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:572) [nukkit-stable.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2345) [nukkit-stable.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:129) [nukkit-stable.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:170) [nukkit-stable.jar:?]
	at cn.nukkit.Server.tick(Server.java:1363) [nukkit-stable.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1146) [nukkit-stable.jar:?]
	at cn.nukkit.Server.start(Server.java:1106) [nukkit-stable.jar:?]
	at cn.nukkit.Server.<init>(Server.java:778) [nukkit-stable.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:200) [nukkit-stable.jar:?]
Caused by: java.lang.NullPointerException
	at me.petterim1.ns.NoSpaceInName.DataPacketReceiveEvent(NoSpaceInName.java:22) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:30) ~[nukkit-stable.jar:?]
```

### 💬 Anything else we should know?

Source code: https://github.com/PetteriM1/NoSpaceInName/blob/main/src/main/java/me.petterim1.ns/NoSpaceInName.java#L22

**Comment by joserobjr** [comment]
I just tried it, having only PowerNukkit and https://cloudburstmc.org/resources/nospaceinname.241/updates#resource-update-1903 but I could not reproduce the issue, my secondary account which has spaces in the name had the spaces removed without raising any exception.

**Comment by joserobjr** [comment]
I guess it is being caused by another plugin in your server.

**Comment by joserobjr** [comment]
I managed to reproduce this issue. It happens when the player that is attempting to join is using an outdated client.

This is a plugin bug because it is assuming that the player received in `DataPacketReceiveEvent` will always have a name defined, but it may be `null`.

**Comment by joserobjr** [comment]
I've sent a pull request which should fix the issue to the author of the plugin.

**Comment by PocketMiner92** [comment]
Where i can Download the Fix?
