### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1342]
# 🐞 I found a bug
 I have tried to fix the IOException Issue.
It works with enter the IP Adress in server.properties.
But now i get this.

```java
[JDA RateLimit-Worker 5] ERROR Requester - There was an exception while executing a REST request
java.net.UnknownHostException: discord.com: Try again
at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
at java.net.InetAddress.getAllByName(InetAddress.java:1193)
at java.net.InetAddress.getAllByName(InetAddress.java:1127)
at okhttp3.Dns.lambda$static$0(Dns.java:39)
at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
at okhttp3.RealCall.execute(RealCall.java:93)
at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:199)
at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:139)
at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:122)
at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:461)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

Can anyone Help me to fix this?
Thank You very much ♥️

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git f9a0d68)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by GoodLucky777** [comment]
Maybe because the plugin that use discord jda can't find the host of discord.com

**Comment by joserobjr** [comment]
In one of my hosts I had issues with name resolution of names that were resolvable all over the internet, I solved it by stopping the `named` service (`sudo systemctl stop named`), after doing that it started resolving names again. Don't ask me why that solved the issue, because I really don't know, lol. Your case may be very different, though.

**Comment by joserobjr** [comment]
In one of my hosts I had issues with name resolution of names that were resolvable all over the internet, I solved it by stopping the `named` service (`sudo systemctl stop named`), after doing that it started resolving names again. Don't ask me why that solved the issue, because I really don't know, lol. Your case may be very different, though.

**Comment by PocketMiner92** [comment]
Youre Method works
Thank You Jose

**Comment by PocketMiner92** [comment]
Which Names?
Now this Error comes again.
I have nothing changed
Can you Show me an Example?
@joserobjr
