### ISSUE TITLE
NPC plugin error

### ISSUE THREAD

**Issue by Happmc2525** [PowerNukkit/PowerNukkit#383]
I am getting an error when using this plugin
https://cloudburstmc.org/resources/npc-slapper.143/

**Comment by joserobjr** [comment]
Hello,

What's the output of the `/about` command? And which error are you getting? Can you add the error message?

**Comment by Happmc2525** [comment]
I get an error when used with gac

11:34:26 [ERROR] Throwing
java.lang.RuntimeException: java.lang.IllegalAccessError: failed to access class kotlin.collections.ArraysUtilJVM from class kotlin.collections.ArraysKt___ArraysJvmKt (kotlin.collections.ArraysUtilJVM is in unnamed module of loader cn.nukkit.plugin.PluginClassLoader @664db2ca; kotlin.collections.ArraysKt___ArraysJvmKt is in unnamed module of loader cn.nukkit.plugin.PluginClassLoader @1b3a9ef4)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:467) [powernukkit.jar:?]        at cn.nukkit.Server.enablePlugin(Server.java:769) [powernukkit.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:758) [powernukkit.jar:?]
        at cn.nukkit.Server.<init>(Server.java:581) [powernukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [powernukkit.jar:?]
Caused by: java.lang.IllegalAccessError: failed to access class kotlin.collections.ArraysUtilJVM from class kotlin.collections.ArraysKt___ArraysJvmKt (kotlin.collections.ArraysUtilJVM is in unnamed module of loader cn.nukkit.plugin.PluginClassLoader @664db2ca; kotlin.collections.ArraysKt___ArraysJvmKt is in unnamed module of loader cn.nukkit.plugin.PluginClassLoader @1b3a9ef4)
        at kotlin.collections.ArraysKt___ArraysJvmKt.asList(_ArraysJvm.kt:129) ~[?:?]
        at kotlin.text.StringsKt__StringsKt.rangesDelimitedBy$StringsKt__StringsKt(Strings.kt:1165) ~[?:?]
        at kotlin.text.StringsKt__StringsKt.rangesDelimitedBy$StringsKt__StringsKt$default(Strings.kt:1163) ~[?:?]
        at kotlin.text.StringsKt__StringsKt.splitToSequence(Strings.kt:1186) ~[?:?]
        at kotlin.text.StringsKt__StringsKt.splitToSequence$default(Strings.kt:1185) ~[?:?]
        at kotlin.text.StringsKt__StringsJVMKt.replace(StringsJVM.kt:76) ~[?:?]
        at kotlin.text.StringsKt__StringsJVMKt.replace$default(StringsJVM.kt:75) ~[?:?]
        at cz.creeperface.nukkit.gac.al.a(Unknown Source) ~[?:?]
        at cz.creeperface.nukkit.gac.GTAnticheat.onEnable(Unknown Source) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:94) ~[powernukkit.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:118) ~[powernukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:463) ~[powernukkit.jar:?]
        ... 4 more

**Comment by Happmc2525** [comment]
> java.lang.IllegalAccessError: failed to access class kotlin.collections.ArraysUtilJVM from class kotlin.collections.ArraysKt___ArraysJvmKt (kotlin.collections.ArraysUtilJVM is in unnamed module of loader cn.nukkit.plugin.PluginClassLoader @664db2ca; kotlin.collections.ArraysKt___ArraysJvmKt is in unnamed module of loader cn.nukkit.plugin.PluginClassLoader @1b3a9ef4)
        at kotlin.collections.ArraysKt___ArraysJvmKt.asList(_ArraysJvm.kt:129)
        at kotlin.text.StringsKt__StringsKt.rangesDelimitedBy$StringsKt__StringsKt(Strings.kt:1165)
        at kotlin.text.StringsKt__StringsKt.rangesDelimitedBy$StringsKt__StringsKt$default(Strings.kt:1163)
        at kotlin.text.StringsKt__StringsKt.splitToSequence(Strings.kt:1186)
        at kotlin.text.StringsKt__StringsKt.splitToSequence$default(Strings.kt:1185)
        at kotlin.text.StringsKt__StringsJVMKt.replace(StringsJVM.kt:76)
        at kotlin.text.StringsKt__StringsJVMKt.replace$default(StringsJVM.kt:75)
        at me.deceitya.siumaikun.utils.MessageContainer.get(MessageContainer.kt:35)
        at me.deceitya.siumaikun.command.SiumaiCommand$execute$1.invokeSuspend(SiumaiCommand.kt:39)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)

**Comment by tuilakhanh** [comment]
@Happmc2525 did you use gac new-raknet version ?

**Comment by Happmc2525** [comment]
@tuilakhanh No, it's a normal version

**Comment by joserobjr** [comment]
Are you using Java 8?

**Comment by tuilakhanh** [comment]
@Happmc2525 try this 

http://nukkitx.eu:8000/GAC-1.0.jar

**Comment by Happmc2525** [comment]
@tuilakhanh Using it also gives an error

**Comment by joserobjr** [comment]
Please, send the link which is generated by /debugpaste, it will show the current configuration, plugins and the recent log. I suspect your environment is misconfigured or has compatibility issues.

**Comment by Happmc2525** [comment]
@joserobjr https://hastebin.com/atecidirow

**Comment by joserobjr** [comment]
@Happmc2525 you are using Java 14 and the issue seems to be caused by the Java module system that were introduced in Java 9. It's recommended to run the server using Java 8.

Please, try to run the server with Java 8, if you get a new error send the updated link with /debugpaste

**Comment by Happmc2525** [comment]
I tried deleting after deleting the GAC file and it worked fine

**Comment by Happmc2525** [comment]
After deleting the GAC file, I tried it and it worked
