### ISSUE TITLE
Server stop responding

### ISSUE THREAD

**Issue by Htepple** [PowerNukkit/PowerNukkit#390]
# 🐞 I found a bug

### 📋 Debug information

* PowerNukkit version: PN-1.3.1.0 (master 19.07.2020)
* Debug link: https://hastebin.com/atizidofaw.rb
* Timings link (if relevant): ✍ 

### 💢 Crash Dump, Stack Trace and Other Files

https://hastebin.com/atizidofaw.rb

**Comment by Htepple** [comment]
mongodb driver

**Comment by joserobjr** [comment]
```java
2020-07-19 11:51:35.984 [Watchdog] FATAL - Current Thread: main
2020-07-19 11:51:35.984 [Watchdog] FATAL - 	PID: 1 | Suspended: false | Native: false | State: RUNNABLE
2020-07-19 11:51:35.984 [Watchdog] FATAL - 	Thread is waiting on monitor(s):
2020-07-19 11:51:35.984 [Watchdog] FATAL - 		Locked on:java.util.zip.Inflater.inflate(Inflater.java:259)
2020-07-19 11:51:35.984 [Watchdog] FATAL - 	Stack:
2020-07-19 11:51:35.985 [Watchdog] FATAL - 		java.util.zip.Inflater.inflateBytes(Native Method)
2020-07-19 11:51:35.985 [Watchdog] FATAL - 		java.util.zip.Inflater.inflate(Inflater.java:259)
2020-07-19 11:51:35.985 [Watchdog] FATAL - 		java.util.zip.Inflater.inflate(Inflater.java:280)
2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.network.Network.inflateRaw(Network.java:80)
2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.network.Network.processBatch(Network.java:217)
2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.Player.handleDataPacket(Player.java:2172)
2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:76)
2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.network.Network.processInterfaces(Network.java:154)
2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.Server.tick(Server.java:1179)
2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.Server.tickProcessor(Server.java:962)
2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.Server.start(Server.java:930)
2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.Server.<init>(Server.java:588)
2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.Nukkit.main(Nukkit.java:120)
```

Always stopping with this stack trace

**Comment by Htepple** [comment]
> ```java
> 2020-07-19 11:51:35.984 [Watchdog] FATAL - Current Thread: main
> 2020-07-19 11:51:35.984 [Watchdog] FATAL - 	PID: 1 | Suspended: false | Native: false | State: RUNNABLE
> 2020-07-19 11:51:35.984 [Watchdog] FATAL - 	Thread is waiting on monitor(s):
> 2020-07-19 11:51:35.984 [Watchdog] FATAL - 		Locked on:java.util.zip.Inflater.inflate(Inflater.java:259)
> 2020-07-19 11:51:35.984 [Watchdog] FATAL - 	Stack:
> 2020-07-19 11:51:35.985 [Watchdog] FATAL - 		java.util.zip.Inflater.inflateBytes(Native Method)
> 2020-07-19 11:51:35.985 [Watchdog] FATAL - 		java.util.zip.Inflater.inflate(Inflater.java:259)
> 2020-07-19 11:51:35.985 [Watchdog] FATAL - 		java.util.zip.Inflater.inflate(Inflater.java:280)
> 2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.network.Network.inflateRaw(Network.java:80)
> 2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.network.Network.processBatch(Network.java:217)
> 2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.Player.handleDataPacket(Player.java:2172)
> 2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:76)
> 2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.network.Network.processInterfaces(Network.java:154)
> 2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.Server.tick(Server.java:1179)
> 2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.Server.tickProcessor(Server.java:962)
> 2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.Server.start(Server.java:930)
> 2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.Server.<init>(Server.java:588)
> 2020-07-19 11:51:35.985 [Watchdog] FATAL - 		cn.nukkit.Nukkit.main(Nukkit.java:120)
> ```
> 
> Always stopping with this stack trace

?

**Comment by joserobjr** [comment]
I saw other cases similar, they all stopped with that same stacktrace

**Comment by Htepple** [comment]
> I saw other cases similar, they all stopped with that same stacktrace

Every 1-2 hours the server stops with this error. The server has a restart every 1.5 hours, it does not help

**Comment by Htepple** [comment]
I think this is mongodb driver issue (in my code).

**Comment by Htepple** [comment]
2020-07-19 11:51:35.971 [Watchdog] FATAL - Current Thread: cluster-ClusterId{value='5f14039d29c168229ed6a57f', description='null'}-127.0.0.1:27017
2020-07-19 11:51:35.971 [Watchdog] FATAL - 	PID: 33 | Suspended: false | Native: false | State: TIMED_WAITING
2020-07-19 11:51:35.971 [Watchdog] FATAL - 	Thread is waiting on monitor(s):
2020-07-19 11:51:35.971 [Watchdog] FATAL - 		Locked on:com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:157)
2020-07-19 11:51:35.971 [Watchdog] FATAL - 	Stack:
2020-07-19 11:51:35.971 [Watchdog] FATAL - 		sun.misc.Unsafe.park(Native Method)
2020-07-19 11:51:35.971 [Watchdog] FATAL - 		java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
2020-07-19 11:51:35.972 [Watchdog] FATAL - 		java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
2020-07-19 11:51:35.972 [Watchdog] FATAL - 		com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.waitForSignalOrTimeout(DefaultServerMonitor.java:229)
2020-07-19 11:51:35.972 [Watchdog] FATAL - 		com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.waitForNext(DefaultServerMonitor.java:210)
2020-07-19 11:51:35.972 [Watchdog] FATAL - 		com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:157)
2020-07-19 11:51:35.972 [Watchdog] FATAL - 		java.lang.Thread.run(Thread.java:748)

**Comment by joserobjr** [comment]
Ok. If it keeps happening, let us know 👍

**Comment by Htepple** [comment]
> Ok. If it keeps happening, let us know 👍

Maybe MobPlugin issue, idk

**Comment by Htepple** [comment]
Can you say something about this stack trace? I'm not sure if the problem is in the plugins, because the build hasn't been changed for a month, only the core. I looked at how people work with mongodb in other plugins, everything is exactly the same for me.

**Comment by joserobjr** [comment]
Possible cause: https://stackoverflow.com/questions/55366393/java-inflater-will-loop-infinitely-sometimes

**Comment by joserobjr** [comment]
I've pushed a possible fix. Please, try it. Also check your log after a few hours and search for this warning:
```
Prevented an infinite loop trying to decompress data.
```

If you find it there, please, send back the full log, I want to know if it was needing input or dictionary.

Thanks

**Comment by joserobjr** [comment]
Was auto-closed, reopening since it still needs testing to make sure it causes no odd side effects

**Comment by Htepple** [comment]
Is this server problem (soft, or machine)? This happens before plugins loaded. https://hastebin.com/ojuyatejoj.apache

**Comment by joserobjr** [comment]
@Htepple it's normal, it's just netty doing different attempts to load the native libraries, but it find a way in the end and log the failed attempts as debug
```java
2020-07-20 19:20:52.370 [main] DEBUG - netty_transport_native_epoll_x86_64 cannot be loaded from java.library.path, now trying export to -Dio.netty.native.workdir: /tmp
(debug stacktrace here)
2020-07-20 19:20:52.375 [main] DEBUG - Successfully loaded the library /tmp/libnetty_transport_native_epoll_x86_642435075499726211361.so
```

**Comment by Htepple** [comment]
> @Htepple it's normal, it's just netty doing different attempts to load the native libraries, but it find a way in the end and log the failed attempts as debug
> 
> ```java
> 2020-07-20 19:20:52.370 [main] DEBUG - netty_transport_native_epoll_x86_64 cannot be loaded from java.library.path, now trying export to -Dio.netty.native.workdir: /tmp
> (debug stacktrace here)
> 2020-07-20 19:20:52.375 [main] DEBUG - Successfully loaded the library /tmp/libnetty_transport_native_epoll_x86_642435075499726211361.so
> ```

But server offline o_O

**Comment by joserobjr** [comment]
Is the server responding to console commands?

Can you get the link that is generated with `/debugpaste`?

**Comment by Htepple** [comment]
https://hastebin.com/cenezeveso now server offline (console if working).

**Comment by Htepple** [comment]
Error screen + no messages in console (with debug)
![image](https://user-images.githubusercontent.com/34367447/87995657-cab85680-caf8-11ea-867e-1f6835b9fc5b.png)

**Comment by Htepple** [comment]
I don't think this is my problem because on 1.14 everything worked fine :/

**Comment by joserobjr** [comment]
Strange, in your link your server seems to be health, running at 20 TPS and some players were talking in chat. Is your nick logged there?

**Comment by joserobjr** [comment]
These are the only things that bough my attention:

One:
```java
2020-07-21 00:57:21.339 [main] INFO  - Загружено (19.299 секунд)! Для справки введите "help" или "?"
2020-07-21 00:57:21.339 [main] FATAL - Exception while invoking run
cn.nukkit.utils.ServerException: CommandSender is not valid
	at cn.nukkit.Server.dispatchCommand(Server.java:787) ~[PowerNukkit-1.3.1.0-PN-SNAPSHOT.jar:?]
	at cn.nukkit.console.NukkitConsole.lambda$runCommand$0(NukkitConsole.java:35) ~[PowerNukkit-1.3.1.0-PN-SNAPSHOT.jar:?]
	at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) [PowerNukkit-1.3.1.0-PN-SNAPSHOT.jar:?]
	at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296) [PowerNukkit-1.3.1.0-PN-SNAPSHOT.jar:?]
	at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277) [PowerNukkit-1.3.1.0-PN-SNAPSHOT.jar:?]
	at cn.nukkit.Server.tick(Server.java:1187) [PowerNukkit-1.3.1.0-PN-SNAPSHOT.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:962) [PowerNukkit-1.3.1.0-PN-SNAPSHOT.jar:?]
	at cn.nukkit.Server.start(Server.java:930) [PowerNukkit-1.3.1.0-PN-SNAPSHOT.jar:?]
	at cn.nukkit.Server.<init>(Server.java:588) [PowerNukkit-1.3.1.0-PN-SNAPSHOT.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:120) [PowerNukkit-1.3.1.0-PN-SNAPSHOT.jar:?]
```

Two:
```java
2020-07-21 01:07:21.940 [main] DEBUG - Tried to equip Item Diamond Pickaxe (278:19)x1 tags:0x0A0000090400656E63680A020000000203006C766C030002020069641200000203006C766C040002020069640F000000 but have Item Diamond Pickaxe (278:20)x1 tags:0x0A0000090400656E63680A020000000203006C766C030002020069641200000203006C766C040002020069640F000000 in target slot
2020-07-21 01:07:25.092 [main] DEBUG - Tried to equip Item Diamond Pickaxe (278:27)x1 tags:0x0A0000090400656E63680A020000000203006C766C030002020069641200000203006C766C040002020069640F000000 but have Item Diamond Pickaxe (278:28)x1 tags:0x0A0000090400656E63680A020000000203006C766C030002020069641200000203006C766C040002020069640F000000 in target slot
2020-07-21 01:07:44.590 [main] DEBUG - Tried to equip Item Diamond Pickaxe (278:50)x1 tags:0x0A0000090400656E63680A020000000203006C766C030002020069641200000203006C766C040002020069640F000000 but have Item Diamond Pickaxe (278:51)x1 tags:0x0A0000090400656E63680A020000000203006C766C030002020069641200000203006C766C040002020069640F000000 in target slot
2020-07-21 01:07:45.641 [main] DEBUG - Tried to equip Item Diamond Pickaxe (278:52)x1 tags:0x0A0000090400656E63680A020000000203006C766C030002020069641200000203006C766C040002020069640F000000 but have Item Diamond Pickaxe (278:53)x1 tags:0x0A0000090400656E63680A020000000203006C766C030002020069641200000203006C766C040002020069640F000000 in target slot
```

But the first could be caused by a plugin bug, the log didn't help to identify the source of the scheduled task (I might make it log the plugin name soon).

The second could be just a small desync, maybe somebody attempted to break a protected block, so the client reduced the durability locally, then the server noticed the desync in the next break attempt and re-synced

**Comment by Htepple** [comment]
Now the server is working +-stably, I don't know what will happen next

**Comment by joserobjr** [comment]
Did the server stopped working again or did you get a log mentioning "Prevented an infinite loop trying to decompress data."?

**Comment by Htepple** [comment]
No logs, but now players crashes and can't join, but it's normal, because that happened from original Nukkit v1.1.
