### ISSUE TITLE
Torch bug

### ISSUE THREAD

**Issue by Happmc2525** [PowerNukkit/PowerNukkit#394]
In the latest bleeding build, the torches appear to be in place but are not.

**Comment by joserobjr** [comment]
Can you show some screen shots, a video or share a sample world?

**Comment by Happmc2525** [comment]
cn.nukkit.blockproperty.exception.InvalidBlockPropertyValueException: Property: torch_facing_direction. Current Value: UNKNOWN, Invalid Value: down. The give BlockFace can't be mapped to TorchFace        at cn.nukkit.block.BlockTorch.setBlockFace(BlockTorch.java:109) ~[powernukkit.jar:?]
        at cn.nukkit.block.BlockTorch.place(BlockTorch.java:78) ~[powernukkit.jar:?]
        at cn.nukkit.level.Level.useItemOn(Level.java:2321) ~[powernukkit.jar:?]
        at cn.nukkit.level.Level.useItemOn(Level.java:2167) ~[powernukkit.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:3238) ~[powernukkit.jar:?]
        at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1510) ~[?:?]
        at cn.nukkit.network.Network.processPackets(Network.java:273) ~[powernukkit.jar:?]
        at cn.nukkit.network.Network.processBatch(Network.java:258) [powernukkit.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2173) [powernukkit.jar:?]
        at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) [GAC-1.0.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:76) [powernukkit.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:158) [powernukkit.jar:?]
        at cn.nukkit.Server.tick(Server.java:1175) [powernukkit.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:958) [powernukkit.jar:?]
        at cn.nukkit.Server.start(Server.java:926) [powernukkit.jar:?]
        at cn.nukkit.Server.<init>(Server.java:584) [powernukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [powernukkit.jar:?]

**Comment by joserobjr** [comment]
Oh, TY

**Comment by joserobjr** [comment]
These torches are annoying lol
