### ISSUE TITLE
Racknet crash

### ISSUE THREAD

**Issue by SenseiTarzan** [PowerNukkit/PowerNukkit#398]
# 🐞 I found a bug

### ▶ Steps to Reproduce

is when I log on after two minutes he crashes with Raknet.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT
* Debug link: ----------
* Timings link (if relevant): ----------

### 💢 Crash Dump, Stack Trace and Other Files

```java
12:29:26 [ERROR] An exception occurred in RakNet
java.net.SocketException: Operation not permitted
        at sun.nio.ch.DatagramChannelImpl.send0(Native Method) ~[?:1.8.0_162]
        at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:521) ~[?:1.8.0_162]
        at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:483) ~[?:1.8.0_162]
        at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:462) ~[?:1.8.0_162]
        at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:292) ~[Nukkit.jar:?]
        at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:142) [Nukkit.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:928) [Nukkit.jar:?]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:356) [Nukkit.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895) [Nukkit.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1383) [Nukkit.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749) [Nukkit.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741) [Nukkit.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.access$2100(AbstractChannelHandlerContext.java:56) [Nukkit.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext$Tasks$4.run(AbstractChannelHandlerContext.java:1177) [Nukkit.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [Nukkit.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416) [Nukkit.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515) [Nukkit.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) [Nukkit.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Nukkit.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

**Comment by joserobjr** [comment]
Apparently it's a system environment setting issue.

https://github.com/netty/netty/issues/1258

Based on the reply quoted bellow, you might need to adjust your iptable rules.

> I have received new equipment and am no longer able to reproduce the problem myself on Ubuntu 12.10, using
> Linux nb-10490 3.5.0-27-generic #46-Ubuntu SMP Mon Mar 25 19:58:17 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
> 
> with the same JDK as before:
> 
> ```
> java version "1.7.0_17"
> Java(TM) SE Runtime Environment (build 1.7.0_17-b02)
> Java HotSpot(TM) 64-Bit Server VM (build 23.7-b01, mixed mode)
> ```
> 
> On this system there are no iptables rules.

**Comment by joserobjr** [comment]
I think this is the iptables adjustment that needs to be done:
https://stackoverflow.com/a/23869102/804976

**Comment by joserobjr** [comment]
More details about the iptables settings: https://stackoverflow.com/a/62624206/804976

Just make sure you configure the port that you are using on the server.
