### ISSUE TITLE
WorldProtect plugin error

### ISSUE THREAD

**Issue by Happmc2525** [PowerNukkit/PowerNukkit#409]
# 🐞 I found a bug
https://github.com/HmmHmmmm/WorldProtect
I am getting this error when using this plugin

19:59:01 [ERROR] Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[powernukkit.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[powernukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:579) [powernukkit.jar:?]
        at cn.nukkit.block.BlockPressurePlateBase.onEntityCollide(BlockPressurePlateBase.java:154) [powernukkit.jar:?]
        at cn.nukkit.Player.checkBlockCollision(Player.java:1423) [powernukkit.jar:?]
        at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:1402) [powernukkit.jar:?]
        at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:232) [powernukkit.jar:?]
        at cn.nukkit.Player.onUpdate(Player.java:1754) [powernukkit.jar:?]
        at cn.nukkit.level.Level.doTick(Level.java:836) [powernukkit.jar:?]
        at cn.nukkit.Server.checkTickUpdates(Server.java:1104) [powernukkit.jar:?]
        at cn.nukkit.Server.tick(Server.java:1186) [powernukkit.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:958) [powernukkit.jar:?]
        at cn.nukkit.Server.start(Server.java:926) [powernukkit.jar:?]
        at cn.nukkit.Server.<init>(Server.java:584) [powernukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [powernukkit.jar:?]
Caused by: java.lang.NullPointerException

### 📋 Debug information
https://hastebin.com/aworipebar

**Comment by Happmc2525** [comment]
It was due to the Skyblock plugin
