### ISSUE TITLE
Could not tick level error: cn.nukkit.block.BlockAir cannot be cast to cn.nukkit.block.BlockDaylightDetector

### ISSUE THREAD

**Issue by good777LUCKY** [PowerNukkit/PowerNukkit#412]
# 🐞 I found a bug

### 📸 Screenshots / Videos

(Image: Chunk loading is broken)
![20200726_192109](https://user-images.githubusercontent.com/43497313/88476664-383f0980-cf75-11ea-951f-b084c673d924.png)

### ▶ Steps to Reproduce

It makes chunk loading issue.

### ✔ Expected Behavior

No errors.

### ❌ Actual Behavior

Errors occurred.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

```
2020-07-26 18:34:38.886 [main] ERROR - "Survival" 레벨의 틱을 처리할 수 없습니다: java.lang.NullPointerException
	at cn.nukkit.utils.BinaryStream.putString(BinaryStream.java:580)
	at cn.nukkit.network.protocol.PlayerListPacket.encode(PlayerListPacket.java:36)
	at cn.nukkit.Server.broadcastPacket(Server.java:660)
	at cn.nukkit.Server.updatePlayerListData(Server.java:1041)
	at cn.nukkit.Server.updatePlayerListData(Server.java:1034)
	at cn.nukkit.entity.EntityHuman.spawnTo(EntityHuman.java:292)
	at cn.nukkit.Player.sendChunk(Player.java:810)
	at cn.nukkit.level.Level.chunkRequestCallback(Level.java:2900)
	at cn.nukkit.level.format.anvil.Anvil.requestChunkTask(Anvil.java:172)
	at cn.nukkit.level.Level.processChunkRequest(Level.java:2873)
	at cn.nukkit.level.Level.doTick(Level.java:885)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1104)
	at cn.nukkit.Server.tick(Server.java:1186)
	at cn.nukkit.Server.tickProcessor(Server.java:958)
	at cn.nukkit.Server.start(Server.java:926)
	at cn.nukkit.Server.<init>(Server.java:584)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)

2020-07-26 18:34:39.126 [main] INFO  - §bkorionic§f[/175.115.237.174:58916]이(가) 개체 ID 2436(으)로 (Survival, 570.5677, 76.0, 2549.9958)에 로그인했습니다
2020-07-26 18:34:39.721 [main] INFO  - [ZChat] Chat format for user korionic || pID 2436 || group level19 || format §l[레벨19§r§l] %name% §r§e>§6>§r %msg%
2020-07-26 18:34:39.726 [main] INFO  - §a§l§f[§e레벨19§f]§a 굳럭키 서버에 오신 것을 환영합니다! korionic님! :D
2020-07-26 18:34:41.723 [main] ERROR - "Survival" 레벨의 틱을 처리할 수 없습니다: java.lang.ClassCastException: cn.nukkit.block.BlockAir cannot be cast to cn.nukkit.block.BlockDaylightDetector
	at cn.nukkit.blockentity.BlockEntityDaylightDetector.onUpdate(BlockEntityDaylightDetector.java:25)
	at cn.nukkit.level.Level.lambda$doTick$1(Level.java:845)
	at java.util.Collection.removeIf(Collection.java:414)
	at cn.nukkit.level.Level.doTick(Level.java:845)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1104)
	at cn.nukkit.Server.tick(Server.java:1186)
	at cn.nukkit.Server.tickProcessor(Server.java:958)
	at cn.nukkit.Server.start(Server.java:926)
	at cn.nukkit.Server.<init>(Server.java:584)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)

2020-07-26 18:34:41.814 [main] ERROR - "Survival" 레벨의 틱을 처리할 수 없습니다: java.lang.ClassCastException: cn.nukkit.block.BlockAir cannot be cast to cn.nukkit.block.BlockDaylightDetector
	at cn.nukkit.blockentity.BlockEntityDaylightDetector.onUpdate(BlockEntityDaylightDetector.java:25)
	at cn.nukkit.level.Level.lambda$doTick$1(Level.java:845)
	at java.util.Collection.removeIf(Collection.java:414)
	at cn.nukkit.level.Level.doTick(Level.java:845)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1104)
	at cn.nukkit.Server.tick(Server.java:1186)
	at cn.nukkit.Server.tickProcessor(Server.java:958)
	at cn.nukkit.Server.start(Server.java:926)
	at cn.nukkit.Server.<init>(Server.java:584)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)

2020-07-26 18:34:41.861 [main] ERROR - "Survival" 레벨의 틱을 처리할 수 없습니다: java.lang.ClassCastException: cn.nukkit.block.BlockAir cannot be cast to cn.nukkit.block.BlockDaylightDetector
	at cn.nukkit.blockentity.BlockEntityDaylightDetector.onUpdate(BlockEntityDaylightDetector.java:25)
	at cn.nukkit.level.Level.lambda$doTick$1(Level.java:845)
	at java.util.Collection.removeIf(Collection.java:414)
	at cn.nukkit.level.Level.doTick(Level.java:845)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1104)
	at cn.nukkit.Server.tick(Server.java:1186)
	at cn.nukkit.Server.tickProcessor(Server.java:958)
	at cn.nukkit.Server.start(Server.java:926)
	at cn.nukkit.Server.<init>(Server.java:584)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)

2020-07-26 18:34:41.908 [main] ERROR - "Survival" 레벨의 틱을 처리할 수 없습니다: java.lang.ClassCastException: cn.nukkit.block.BlockAir cannot be cast to cn.nukkit.block.BlockDaylightDetector
	at cn.nukkit.blockentity.BlockEntityDaylightDetector.onUpdate(BlockEntityDaylightDetector.java:25)
	at cn.nukkit.level.Level.lambda$doTick$1(Level.java:845)
	at java.util.Collection.removeIf(Collection.java:414)
	at cn.nukkit.level.Level.doTick(Level.java:845)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1104)
	at cn.nukkit.Server.tick(Server.java:1186)
	at cn.nukkit.Server.tickProcessor(Server.java:958)
	at cn.nukkit.Server.start(Server.java:926)
	at cn.nukkit.Server.<init>(Server.java:584)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)

2020-07-26 18:34:41.956 [main] ERROR - "Survival" 레벨의 틱을 처리할 수 없습니다: java.lang.ClassCastException: cn.nukkit.block.BlockAir cannot be cast to cn.nukkit.block.BlockDaylightDetector
	at cn.nukkit.blockentity.BlockEntityDaylightDetector.onUpdate(BlockEntityDaylightDetector.java:25)
	at cn.nukkit.level.Level.lambda$doTick$1(Level.java:845)
	at java.util.Collection.removeIf(Collection.java:414)
	at cn.nukkit.level.Level.doTick(Level.java:845)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1104)
	at cn.nukkit.Server.tick(Server.java:1186)
	at cn.nukkit.Server.tickProcessor(Server.java:958)
	at cn.nukkit.Server.start(Server.java:926)
	at cn.nukkit.Server.<init>(Server.java:584)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)

2020-07-26 18:34:41.996 [main] ERROR - "Survival" 레벨의 틱을 처리할 수 없습니다: java.lang.ClassCastException: cn.nukkit.block.BlockAir cannot be cast to cn.nukkit.block.BlockDaylightDetector
	at cn.nukkit.blockentity.BlockEntityDaylightDetector.onUpdate(BlockEntityDaylightDetector.java:25)
	at cn.nukkit.level.Level.lambda$doTick$1(Level.java:845)
	at java.util.Collection.removeIf(Collection.java:414)
	at cn.nukkit.level.Level.doTick(Level.java:845)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1104)
	at cn.nukkit.Server.tick(Server.java:1186)
	at cn.nukkit.Server.tickProcessor(Server.java:958)
	at cn.nukkit.Server.start(Server.java:926)
	at cn.nukkit.Server.<init>(Server.java:584)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)

2020-07-26 18:34:42.006 [main] ERROR - "Survival" 레벨의 틱을 처리할 수 없습니다: java.lang.ClassCastException: cn.nukkit.block.BlockAir cannot be cast to cn.nukkit.block.BlockDaylightDetector
	at cn.nukkit.blockentity.BlockEntityDaylightDetector.onUpdate(BlockEntityDaylightDetector.java:25)
	at cn.nukkit.level.Level.lambda$doTick$1(Level.java:845)
	at java.util.Collection.removeIf(Collection.java:414)
	at cn.nukkit.level.Level.doTick(Level.java:845)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1104)
	at cn.nukkit.Server.tick(Server.java:1186)
	at cn.nukkit.Server.tickProcessor(Server.java:958)
	at cn.nukkit.Server.start(Server.java:926)
	at cn.nukkit.Server.<init>(Server.java:584)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)

2020-07-26 18:34:42.016 [main] ERROR - "Survival" 레벨의 틱을 처리할 수 없습니다: java.lang.ClassCastException: cn.nukkit.block.BlockAir cannot be cast to cn.nukkit.block.BlockDaylightDetector
	at cn.nukkit.blockentity.BlockEntityDaylightDetector.onUpdate(BlockEntityDaylightDetector.java:25)
	at cn.nukkit.level.Level.lambda$doTick$1(Level.java:845)
	at java.util.Collection.removeIf(Collection.java:414)
	at cn.nukkit.level.Level.doTick(Level.java:845)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1104)
	at cn.nukkit.Server.tick(Server.java:1186)
	at cn.nukkit.Server.tickProcessor(Server.java:958)
	at cn.nukkit.Server.start(Server.java:926)
	at cn.nukkit.Server.<init>(Server.java:584)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)

2020-07-26 18:34:42.027 [main] ERROR - "Survival" 레벨의 틱을 처리할 수 없습니다: java.lang.ClassCastException: cn.nukkit.block.BlockAir cannot be cast to cn.nukkit.block.BlockDaylightDetector
	at cn.nukkit.blockentity.BlockEntityDaylightDetector.onUpdate(BlockEntityDaylightDetector.java:25)
	at cn.nukkit.level.Level.lambda$doTick$1(Level.java:845)
	at java.util.Collection.removeIf(Collection.java:414)
	at cn.nukkit.level.Level.doTick(Level.java:845)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1104)
	at cn.nukkit.Server.tick(Server.java:1186)
	at cn.nukkit.Server.tickProcessor(Server.java:958)
	at cn.nukkit.Server.start(Server.java:926)
	at cn.nukkit.Server.<init>(Server.java:584)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)

2020-07-26 18:34:42.037 [main] ERROR - "Survival" 레벨의 틱을 처리할 수 없습니다: java.lang.ClassCastException: cn.nukkit.block.BlockAir cannot be cast to cn.nukkit.block.BlockDaylightDetector
	at cn.nukkit.blockentity.BlockEntityDaylightDetector.onUpdate(BlockEntityDaylightDetector.java:25)
	at cn.nukkit.level.Level.lambda$doTick$1(Level.java:845)
	at java.util.Collection.removeIf(Collection.java:414)
	at cn.nukkit.level.Level.doTick(Level.java:845)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1104)
	at cn.nukkit.Server.tick(Server.java:1186)
	at cn.nukkit.Server.tickProcessor(Server.java:958)
	at cn.nukkit.Server.start(Server.java:926)
	at cn.nukkit.Server.<init>(Server.java:584)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)

2020-07-26 18:34:42.048 [main] ERROR - "Survival" 레벨의 틱을 처리할 수 없습니다: java.lang.ClassCastException: cn.nukkit.block.BlockAir cannot be cast to cn.nukkit.block.BlockDaylightDetector
	at cn.nukkit.blockentity.BlockEntityDaylightDetector.onUpdate(BlockEntityDaylightDetector.java:25)
	at cn.nukkit.level.Level.lambda$doTick$1(Level.java:845)
	at java.util.Collection.removeIf(Collection.java:414)
	at cn.nukkit.level.Level.doTick(Level.java:845)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1104)
	at cn.nukkit.Server.tick(Server.java:1186)
	at cn.nukkit.Server.tickProcessor(Server.java:958)
	at cn.nukkit.Server.start(Server.java:926)
	at cn.nukkit.Server.<init>(Server.java:584)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)

2020-07-26 18:34:42.058 [main] ERROR - "Survival" 레벨의 틱을 처리할 수 없습니다: java.lang.ClassCastException: cn.nukkit.block.BlockAir cannot be cast to cn.nukkit.block.BlockDaylightDetector
	at cn.nukkit.blockentity.BlockEntityDaylightDetector.onUpdate(BlockEntityDaylightDetector.java:25)
	at cn.nukkit.level.Level.lambda$doTick$1(Level.java:845)
	at java.util.Collection.removeIf(Collection.java:414)
	at cn.nukkit.level.Level.doTick(Level.java:845)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1104)
	at cn.nukkit.Server.tick(Server.java:1186)
	at cn.nukkit.Server.tickProcessor(Server.java:958)
	at cn.nukkit.Server.start(Server.java:926)
	at cn.nukkit.Server.<init>(Server.java:584)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)

2020-07-26 18:34:42.068 [main] ERROR - "Survival" 레벨의 틱을 처리할 수 없습니다: java.lang.ClassCastException: cn.nukkit.block.BlockAir cannot be cast to cn.nukkit.block.BlockDaylightDetector
	at cn.nukkit.blockentity.BlockEntityDaylightDetector.onUpdate(BlockEntityDaylightDetector.java:25)
	at cn.nukkit.level.Level.lambda$doTick$1(Level.java:845)
	at java.util.Collection.removeIf(Collection.java:414)
	at cn.nukkit.level.Level.doTick(Level.java:845)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1104)
	at cn.nukkit.Server.tick(Server.java:1186)
	at cn.nukkit.Server.tickProcessor(Server.java:958)
	at cn.nukkit.Server.start(Server.java:926)
	at cn.nukkit.Server.<init>(Server.java:584)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)

2020-07-26 18:34:42.079 [main] ERROR - "Survival" 레벨의 틱을 처리할 수 없습니다: java.lang.ClassCastException: cn.nukkit.block.BlockAir cannot be cast to cn.nukkit.block.BlockDaylightDetector
	at cn.nukkit.blockentity.BlockEntityDaylightDetector.onUpdate(BlockEntityDaylightDetector.java:25)
	at cn.nukkit.level.Level.lambda$doTick$1(Level.java:845)
	at java.util.Collection.removeIf(Collection.java:414)
	at cn.nukkit.level.Level.doTick(Level.java:845)
	at cn.nukkit.Server.checkTickUpdates(Server.java:1104)
	at cn.nukkit.Server.tick(Server.java:1186)
	at cn.nukkit.Server.tickProcessor(Server.java:958)
	at cn.nukkit.Server.start(Server.java:926)
	at cn.nukkit.Server.<init>(Server.java:584)
	at cn.nukkit.Nukkit.main(Nukkit.java:120)
```

### 💬 Anything else we should know?

`레벨의 틱을 처리할 수 없습니다` means `Could not tick level`.

**Comment by good777LUCKY** [comment]
I found why did error occur. It was because I replace daylight sensors to air with worldedit, but blockentity doesn't disappear. BlockEntity was ticking it.

**Comment by joserobjr** [comment]
Thank you for reporting!
