### ISSUE TITLE
TNTRun plugin error

### ISSUE THREAD

**Issue by Happmc2525** [PowerNukkit/PowerNukkit#414]
# 🔌 Plugin compatibility issue
I get this error when I put a minecart

### 📋 Debug information
https://debugpaste.powernukkit.org/pastes/ubobazenuc

### 💢 Crash Dump, Stack Trace and Other Files
```java
08:37:20 [FATAL] "TNTRun v2.3.3"に"cn.nukkit.event.entity.EntityDamageByEntityEvent"Eventを渡すことができませんでした: suomicraftpe.tntrun.a.aでのnull
08:37:20 [ERROR] Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[powernukkit.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[powernukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:579) ~[powernukkit.jar:?]
        at cn.nukkit.entity.Entity.attack(Entity.java:1186) ~[powernukkit.jar:?]
        at cn.nukkit.entity.item.EntityVehicle.attack(EntityVehicle.java:135) ~[powernukkit.jar:?]
        at cn.nukkit.entity.item.EntityMinecartAbstract.attack(EntityMinecartAbstract.java:247) ~[powernukkit.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:3415) ~[powernukkit.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_252]
        at cn.nukkit.network.Network.processPackets(Network.java:273) [powernukkit.jar:?]
        at cn.nukkit.network.Network.processBatch(Network.java:258) [powernukkit.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2173) [powernukkit.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:76) [powernukkit.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:158) [powernukkit.jar:?]
        at cn.nukkit.Server.tick(Server.java:1175) [powernukkit.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:958) [powernukkit.jar:?]
        at cn.nukkit.Server.start(Server.java:926) [powernukkit.jar:?]
        at cn.nukkit.Server.<init>(Server.java:584) [powernukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [powernukkit.jar:?]
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_252]
	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964) ~[?:1.8.0_252]
	at suomicraftpe.tntrun.a.a.a(Arena.java:343) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[powernukkit.jar:?]
	... 17 more
```

**Comment by joserobjr** [comment]
Reported Version: cac2328
Plugin: https://cloudburstmc.org/resources/tntrun.106/

**Comment by joserobjr** [comment]
# Investigation 
Player.handleDataPacket(Player.java:3415):
https://github.com/PowerNukkit/PowerNukkit/blob/cac23287781bf9755beebfd40b7b982e705dbe8c/src/main/java/cn/nukkit/Player.java#L3389-L3419

EntityMinecartAbstract.attack(EntityMinecartAbstract.java:247):
https://github.com/PowerNukkit/PowerNukkit/blob/cac23287781bf9755beebfd40b7b982e705dbe8c/src/main/java/cn/nukkit/entity/item/EntityMinecartAbstract.java#L240-L255

EntityVehicle.attack(EntityVehicle.java:135):
https://github.com/PowerNukkit/PowerNukkit/blob/cac23287781bf9755beebfd40b7b982e705dbe8c/src/main/java/cn/nukkit/entity/item/EntityVehicle.java#L86-L136

Entity.attack(Entity.java:1186):
https://github.com/PowerNukkit/PowerNukkit/blob/cac23287781bf9755beebfd40b7b982e705dbe8c/src/main/java/cn/nukkit/entity/Entity.java#L1178-L1196

suomicraftpe.tntrun.a.a.a(Arena.java:343)
```java
    @EventHandler
    private void a(EntityDamageEvent e) {
        if (this.a.containsKey(e.getEntity().getName()) && DamageCause.VOID != e.getCause()) {
            e.setCancelled(true);
        }

    }
```

# Diagnostic
`e.getEntity().getName()` returned `null`

**Comment by joserobjr** [comment]
The exception has been fixed. Thank you for reporting 👍
