### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by Happmc2525** [PowerNukkit/PowerNukkit#471]
# 🐞 I found a bug
I get this error when starting powernukkit

```
10:04:15 [ERROR] Found an unknown BlockId:Meta combination: 473:3 - minecraft:bee_nest;nukkit-legacy=3 - BlockProperties{bitSize=6, properties=[0-6:nukkit-legacy]} - minecraft:bee_nest, replacing with an "UPDATE!" block.
10:04:15 [WARN ] Attempted to get an illegal item block -218:3 (473), the runtime id was unknown and the meta was changed to 0
10:04:15 [ERROR] Error getting the item -218:3 (473)! Returning an unsafe item stack!
java.lang.ArrayIndexOutOfBoundsException: -13952
        at cn.nukkit.blockstate.BlockStateRegistry.getProperties(BlockStateRegistry.java:345) ~[powernukkit.jar:?]
        at cn.nukkit.blockstate.BlockState.getProperties(BlockState.java:196) ~[powernukkit.jar:?]        at cn.nukkit.blockstate.BlockState.forItem(BlockState.java:178) ~[powernukkit.jar:?]
        at cn.nukkit.blockstate.IBlockState.asItemBlock(IBlockState.java:183) ~[powernukkit.jar:?]        at cn.nukkit.item.Item.get(Item.java:502) [powernukkit.jar:?]
        at cn.nukkit.item.Item.fromJson(Item.java:570) [powernukkit.jar:?]
        at cn.nukkit.item.Item.initCreativeItems(Item.java:378) [powernukkit.jar:?]
        at cn.nukkit.item.Item.init(Item.java:363) [powernukkit.jar:?]
        at cn.nukkit.Server.<init>(Server.java:571) [powernukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [powernukkit.jar:?]
10:04:15 [ERROR] Found an unknown BlockId:Meta combination: 474:3 - minecraft:beehive;nukkit-legacy=3 - BlockProperties{bitSize=6, properties=[0-6:nukkit-legacy]} - minecraft:beehive, replacing with an "UPDATE!" block.
10:04:15 [WARN ] Attempted to get an illegal item block -219:3 (474), the runtime id was unknown and the meta was changed to 0
10:04:15 [ERROR] Error getting the item -219:3 (474)! Returning an unsafe item stack!
java.lang.ArrayIndexOutOfBoundsException: -14016
        at cn.nukkit.blockstate.BlockStateRegistry.getProperties(BlockStateRegistry.java:345) ~[powernukkit.jar:?]
        at cn.nukkit.blockstate.BlockState.getProperties(BlockState.java:196) ~[powernukkit.jar:?]        at cn.nukkit.blockstate.BlockState.forItem(BlockState.java:178) ~[powernukkit.jar:?]
        at cn.nukkit.blockstate.IBlockState.asItemBlock(IBlockState.java:183) ~[powernukkit.jar:?]        at cn.nukkit.item.Item.get(Item.java:502) [powernukkit.jar:?]
        at cn.nukkit.item.Item.fromJson(Item.java:570) [powernukkit.jar:?]
        at cn.nukkit.item.Item.initCreativeItems(Item.java:378) [powernukkit.jar:?]
        at cn.nukkit.item.Item.init(Item.java:363) [powernukkit.jar:?]
        at cn.nukkit.Server.<init>(Server.java:571) [powernukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [powernukkit.jar:?]
10:04:15 [INFO ] Loading recipes...
10:04:15 [WARN ] Attempted to get an illegal item block -219:3 (474), the runtime id was unknown and the meta was changed to 0
10:04:15 [ERROR] Error getting the item -219:3 (474)! Returning an unsafe item stack!
java.lang.ArrayIndexOutOfBoundsException: -14016
        at cn.nukkit.blockstate.BlockStateRegistry.getProperties(BlockStateRegistry.java:345) ~[powernukkit.jar:?]
        at cn.nukkit.blockstate.BlockState.getProperties(BlockState.java:196) ~[powernukkit.jar:?]        at cn.nukkit.blockstate.BlockState.forItem(BlockState.java:178) ~[powernukkit.jar:?]
        at cn.nukkit.blockstate.IBlockState.asItemBlock(IBlockState.java:183) ~[powernukkit.jar:?]        at cn.nukkit.item.Item.get(Item.java:502) [powernukkit.jar:?]
        at cn.nukkit.item.Item.fromJson(Item.java:570) [powernukkit.jar:?]
        at cn.nukkit.inventory.CraftingManager.loadRecipes(CraftingManager.java:150) [powernukkit.jar:?]
        at cn.nukkit.inventory.CraftingManager.<init>(CraftingManager.java:67) [powernukkit.jar:?]        at cn.nukkit.Server.<init>(Server.java:590) [powernukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [powernukkit.jar:?]
10:04:15 [WARN ] Attempted to get an illegal item block -219:3 (474), the runtime id was unknown and the meta was changed to 0
10:04:15 [ERROR] Error getting the item -219:3 (474)! Returning an unsafe item stack!
java.lang.ArrayIndexOutOfBoundsException: -14016
        at cn.nukkit.blockstate.BlockStateRegistry.getProperties(BlockStateRegistry.java:345) ~[powernukkit.jar:?]
        at cn.nukkit.blockstate.BlockState.getProperties(BlockState.java:196) ~[powernukkit.jar:?]        at cn.nukkit.blockstate.BlockState.forItem(BlockState.java:178) ~[powernukkit.jar:?]
        at cn.nukkit.blockstate.IBlockState.asItemBlock(IBlockState.java:183) ~[powernukkit.jar:?]        at cn.nukkit.item.Item.get(Item.java:502) [powernukkit.jar:?]
        at cn.nukkit.item.Item.fromJson(Item.java:570) [powernukkit.jar:?]
        at cn.nukkit.inventory.CraftingManager.loadRecipes(CraftingManager.java:150) [powernukkit.jar:?]
        at cn.nukkit.inventory.CraftingManager.<init>(CraftingManager.java:67) [powernukkit.jar:?]        at cn.nukkit.Server.<init>(Server.java:590) [powernukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [powernukkit.jar:?]
10:04:15 [WARN ] Attempted to get an illegal item block -219:3 (474), the runtime id was unknown and the meta was changed to 0
10:04:15 [ERROR] Error getting the item -219:3 (474)! Returning an unsafe item stack!
java.lang.ArrayIndexOutOfBoundsException: -14016
        at cn.nukkit.blockstate.BlockStateRegistry.getProperties(BlockStateRegistry.java:345) ~[powernukkit.jar:?]
        at cn.nukkit.blockstate.BlockState.getProperties(BlockState.java:196) ~[powernukkit.jar:?]        at cn.nukkit.blockstate.BlockState.forItem(BlockState.java:178) ~[powernukkit.jar:?]
        at cn.nukkit.blockstate.IBlockState.asItemBlock(IBlockState.java:183) ~[powernukkit.jar:?]        at cn.nukkit.item.Item.get(Item.java:502) [powernukkit.jar:?]
        at cn.nukkit.item.Item.fromJson(Item.java:570) [powernukkit.jar:?]
        at cn.nukkit.inventory.CraftingManager.loadRecipes(CraftingManager.java:150) [powernukkit.jar:?]
        at cn.nukkit.inventory.CraftingManager.<init>(CraftingManager.java:67) [powernukkit.jar:?]        at cn.nukkit.Server.<init>(Server.java:590) [powernukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [powernukkit.jar:?]
```

### 📋 Debug information
* Debug link: https://debugpaste.powernukkit.org/pastes/olokumapib

**Comment by joserobjr** [comment]
Did you use the same world in 1.3.1.4-PN-SNAPSHOT and 1.4.0.0-SNAPSHOT?

The 1.4 don't have the beehive changes yet

**Comment by joserobjr** [comment]
It might be fixed now
