### ISSUE TITLE
Some chunks are not loaded

### ISSUE THREAD

**Issue by Happmc2525** [PowerNukkit/PowerNukkit#482]
# 🐞 I found a bug
I had this bug in the latest bleeding build

### 📋 Debug information
* Debug link: https://debugpaste.powernukkit.org/pastes/mozajeveki

### 💢 Crash Dump, Stack Trace and Other Files
```java
[ERROR] ワールド "world" をチェックすることができませんでした: cn.nukkit.blockproperty.exception.InvalidBlockPropertyMetaException: Property: new_leaf_type. Current Meta: 11, Invalid Meta: 3
        at cn.nukkit.blockproperty.BlockProperty.validateMeta(BlockProperty.java:268)
        at cn.nukkit.blockstate.IntMutableBlockState.validate(IntMutableBlockState.java:82)
        at cn.nukkit.blockstate.IntMutableBlockState.setDataStorage(IntMutableBlockState.java:63)
        at cn.nukkit.block.Block.setDataStorage(Block.java:1536)
        at cn.nukkit.blockstate.IBlockState.getBlock(IBlockState.java:119)
        at cn.nukkit.level.Level.getBlock(Level.java:1577)
        at cn.nukkit.level.Level.getBlock(Level.java:1551)
        at cn.nukkit.block.Block.getSideAtLayer(Block.java:1178)
        at cn.nukkit.block.Block.getSide(Block.java:1169)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.onUpdate(BlockLeaves.java:182)
        at cn.nukkit.level.Level.tickChunks(Level.java:1163)
        at cn.nukkit.level.Level.doTick(Level.java:850)
        at cn.nukkit.Server.checkTickUpdates(Server.java:1208)
        at cn.nukkit.Server.tick(Server.java:1290)
        at cn.nukkit.Server.tickProcessor(Server.java:1062)
        at cn.nukkit.Server.start(Server.java:1030)
        at cn.nukkit.Server.<init>(Server.java:691)
        at cn.nukkit.Nukkit.main(Nukkit.java:120)
Caused by: java.lang.IndexOutOfBoundsException: index (3) must be less than size (2)
        at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1348)
        at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1330)
        at cn.nukkit.blockproperty.ArrayBlockProperty.validateMeta(ArrayBlockProperty.java:139)
        at cn.nukkit.blockproperty.BlockProperty.validateMeta(BlockProperty.java:266)
        ... 24 more

18:34:46 [ERROR] ワールド "world" をチェックすることができませんでした: cn.nukkit.blockproperty.exception.InvalidBlockPropertyMetaException: Property: new_leaf_type. Current Meta: 11, Invalid Meta: 3
        at cn.nukkit.blockproperty.BlockProperty.validateMeta(BlockProperty.java:268)
        at cn.nukkit.blockstate.IntMutableBlockState.validate(IntMutableBlockState.java:82)
        at cn.nukkit.blockstate.IntMutableBlockState.setDataStorage(IntMutableBlockState.java:63)
        at cn.nukkit.block.Block.setDataStorage(Block.java:1536)
        at cn.nukkit.blockstate.IBlockState.getBlock(IBlockState.java:119)
        at cn.nukkit.level.Level.getBlock(Level.java:1577)
        at cn.nukkit.level.Level.getBlock(Level.java:1551)
        at cn.nukkit.block.Block.getSideAtLayer(Block.java:1178)
        at cn.nukkit.block.Block.getSide(Block.java:1169)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.onUpdate(BlockLeaves.java:182)
        at cn.nukkit.level.Level.tickChunks(Level.java:1163)
        at cn.nukkit.level.Level.doTick(Level.java:850)
        at cn.nukkit.Server.checkTickUpdates(Server.java:1208)
        at cn.nukkit.Server.tick(Server.java:1290)
        at cn.nukkit.Server.tickProcessor(Server.java:1062)
        at cn.nukkit.Server.start(Server.java:1030)
        at cn.nukkit.Server.<init>(Server.java:691)
        at cn.nukkit.Nukkit.main(Nukkit.java:120)
Caused by: java.lang.IndexOutOfBoundsException: index (3) must be less than size (2)
        at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1348)
        at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1330)
        at cn.nukkit.blockproperty.ArrayBlockProperty.validateMeta(ArrayBlockProperty.java:139)
        at cn.nukkit.blockproperty.BlockProperty.validateMeta(BlockProperty.java:266)
        ... 19 more
```

**Comment by good777LUCKY** [comment]
I have same problem, it says same errors and cannot tick it.

**Comment by good777LUCKY** [comment]
Also, this error occur lag too much. When I go to unloading chunk, error will spam console.

**Comment by joserobjr** [comment]
をチェックすることができませんでした = nukkit.level.tickError

**Comment by joserobjr** [comment]
Thank you for reporting!

**Comment by Happmc2525** [comment]
Also happens in latest bleeding build
![Screenshot_20200824-125548](https://user-images.githubusercontent.com/60919012/91002347-5e55d900-e609-11ea-9214-7b7cdccaf92d.png)
