### ISSUE TITLE
Cannot tick level error

### ISSUE THREAD

**Issue by good777LUCKY** [PowerNukkit/PowerNukkit#497]
# 🐞 I found a bug

### 📸 Screenshots / Videos

-

### ▶ Steps to Reproduce

1. Go somewhere
2. See errors

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-SNAPSHOT https://github.com/PowerNukkit/PowerNukkit/commit/94cc77b76f1dbbf46a6aebeadc490d7113a4352d
* Debug link: 
* Timings link (if relevant): 

### 💢 Crash Dump, Stack Trace and Other Files

![Screenshot_.jpg](https://user-images.githubusercontent.com/43497313/90598669-76ef7900-e22e-11ea-9629-5848b66518ac.jpg)

### 💬 Anything else we should know?

-

**Comment by joserobjr** [comment]
Hi, thank you for the report. I think the issue you were experiencing was a side-effect of the #482 issue. I've pushed a fix that replaces any broken state with an update block and the issue #482 was resolved today.

Can you check if your issue was resolved using this build or newer? Make sure to backup your world.
https://github.com/PowerNukkit/PowerNukkit/actions/runs/217540566

**Comment by good777LUCKY** [comment]
Now I have this error,
```
2020-08-21 13:59:44.174 [main] FATAL - An error has occurred while trying to get the stateId of state: 161:11 - BlockProperties{bitSize=4, properties=[0-2:new_leaf_type, 2-3:persistent_bit, 3-4:update_bit]} - minecraft:leaves2
java.lang.ArrayIndexOutOfBoundsException: 3
	at cn.nukkit.blockproperty.ArrayBlockProperty.getPersistenceValueForMeta(ArrayBlockProperty.java:149) ~[powernukkit.jar:?]
	at cn.nukkit.blockproperty.BlockProperty.getPersistenceValue(BlockProperty.java:218) ~[powernukkit.jar:?]
	at cn.nukkit.blockproperty.BlockProperties.getPersistenceValue(BlockProperties.java:350) ~[powernukkit.jar:?]
	at cn.nukkit.blockstate.BlockState$IntStorage.getPersistenceValue(BlockState.java:443) ~[powernukkit.jar:?]
	at cn.nukkit.blockstate.BlockState.getPersistenceValue(BlockState.java:240) ~[powernukkit.jar:?]
	at cn.nukkit.blockstate.IBlockState.lambda$getStateId$0(IBlockState.java:89) ~[powernukkit.jar:?]
	at java.util.LinkedHashMap$LinkedKeySet.forEach(LinkedHashMap.java:559) ~[?:1.8.0_265]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082) ~[?:1.8.0_265]
	at cn.nukkit.blockstate.IBlockState.getStateId(IBlockState.java:89) ~[powernukkit.jar:?]
	at cn.nukkit.blockstate.BlockStateRegistry.findRegistrationByStateId(BlockStateRegistry.java:251) ~[powernukkit.jar:?]
	at cn.nukkit.blockstate.BlockStateRegistry.findRegistration(BlockStateRegistry.java:242) ~[powernukkit.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688) [?:1.8.0_265]
	at cn.nukkit.blockstate.BlockStateRegistry.getRegistration(BlockStateRegistry.java:216) [powernukkit.jar:?]
	at cn.nukkit.blockstate.BlockStateRegistry.getRuntimeId(BlockStateRegistry.java:212) [powernukkit.jar:?]
	at cn.nukkit.blockstate.IBlockState.getRuntimeId(IBlockState.java:144) [powernukkit.jar:?]
	at cn.nukkit.level.format.anvil.util.BlockStorage.setBlockState(BlockStorage.java:178) [powernukkit.jar:?]
	at cn.nukkit.level.format.anvil.util.BlockStorage.setBlockState(BlockStorage.java:129) [powernukkit.jar:?]
	at cn.nukkit.level.format.anvil.ChunkSection.loadStorage(ChunkSection.java:142) [powernukkit.jar:?]
	at cn.nukkit.level.format.anvil.ChunkSection.<init>(ChunkSection.java:90) [powernukkit.jar:?]
	at cn.nukkit.level.format.anvil.Chunk.<init>(Chunk.java:71) [powernukkit.jar:?]
	at cn.nukkit.level.format.anvil.Chunk.fromBinary(Chunk.java:226) [powernukkit.jar:?]
	at cn.nukkit.level.format.anvil.RegionLoader.unserializeChunk(RegionLoader.java:86) [powernukkit.jar:?]
	at cn.nukkit.level.format.anvil.RegionLoader.readChunk(RegionLoader.java:71) [powernukkit.jar:?]
	at cn.nukkit.level.format.anvil.RegionLoader.readChunk(RegionLoader.java:19) [powernukkit.jar:?]
	at cn.nukkit.level.format.anvil.Anvil.loadChunk(Anvil.java:212) [powernukkit.jar:?]
	at cn.nukkit.level.format.generic.BaseLevelProvider.getChunk(BaseLevelProvider.java:396) [powernukkit.jar:?]
	at cn.nukkit.level.Level.forceLoadChunk(Level.java:3004) [powernukkit.jar:?]
	at cn.nukkit.level.Level.getChunk(Level.java:2664) [powernukkit.jar:?]
	at cn.nukkit.level.Level.populateChunk(Level.java:3242) [powernukkit.jar:?]
	at cn.nukkit.level.Level.populateChunk(Level.java:3233) [powernukkit.jar:?]
	at cn.nukkit.Player.sendNextChunk(Player.java:841) [powernukkit.jar:?]
	at cn.nukkit.Player.checkNetwork(Player.java:1924) [powernukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1293) [powernukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1062) [powernukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1030) [powernukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:691) [powernukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:120) [powernukkit.jar:?]
```
