### ISSUE TITLE
GAC Fly detection issue

### ISSUE THREAD

**Issue by joserobjr** [PowerNukkit/PowerNukkit#530]
# 🔌 Plugin compatibility issue

It was reported that when GAC rubberband players that it thinks is fly hacking, a NullPointerException floods the log and the console.

After a while, players become unable to join the server.

### 📸 Screenshots / Videos

None yet.

### ▶ Steps to Reproduce

Unknown yet.

### ✔ Expected Behavior

To be defined

### ❌ Actual Behavior

Spam exception and makes the server hangs overtime

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN at 0a3e47a
* Debug link: https://debugpaste.powernukkit.org/pastes/uterugupik.html

### 💢 Crash Dump, Stack Trace and Other Files

```java
2020-08-27 12:52:30.524 [main] WARN  - Error whilst processing the packet 19:MovePlayerPacket for <playerName> (full data: MovePlayerPacket(eid=60500, x=<pos>, y=<pos>, z=<pos>, yaw=-20.889954, headYaw=339.11005, pitch=54.265854, mode=0, onGround=false, ridingEid=0, int1=0, int2=0))
java.lang.NullPointerException: null
    at cn.nukkit.Player.sendPosition(Player.java:4491) ~[server.jar:?]
    at cn.nukkit.Player.sendPosition(Player.java:4485) ~[server.jar:?]
    at cz.creeperface.nukkit.gac.V.a(Unknown Source) ~[?:?]
    at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
    at cn.nukkit.network.Network.lambda$processPackets$3(Network.java:285) ~[server.jar:?]
    at java.util.ArrayList.forEach(ArrayList.java:1259) [?:1.8.0_262]
    at cn.nukkit.network.Network.processPackets(Network.java:283) [server.jar:?]
    at cn.nukkit.network.Network.processBatch(Network.java:269) [server.jar:?]
    at cn.nukkit.Player.handleDataPacket(Player.java:2200) [server.jar:?]
    at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) [GAC-1.0.jar:?]
    at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:75) [server.jar:?]
    at cn.nukkit.network.Network.processInterfaces(Network.java:158) [server.jar:?]
    at cn.nukkit.Server.tick(Server.java:1297) [server.jar:?]
    at cn.nukkit.Server.tickProcessor(Server.java:1080) [server.jar:?]
    at cn.nukkit.Server.start(Server.java:1048) [server.jar:?]
    at cn.nukkit.Server.<init>(Server.java:704) [server.jar:?]
    at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]
```

**Comment by joserobjr** [comment]
Possible cause:
https://github.com/Creeperface01/GAC/blob/2dfeb39616e372ef43f5092e8af4a060b8dc8fbd/src/main/java/cz/creeperface/nukkit/gac/player/CheatPlayer.kt#L98-L100

GAC is not doing a null check before calling `this.sendPosition(forceMovement, ...`, `forceMovement` is a nullable java field and Kotlin is treating the field as a platform type (which disables the null safety feature)

**Comment by joserobjr** [comment]
I opened an issue at GAC reporting the problem: https://github.com/Creeperface01/GAC/issues/20

**Comment by RealTriassic** [comment]
also don't forget this:

15:35:33 [FATAL] Exception while invoking run
java.lang.NullPointerException: cheatData.lastPos.getLevel() must not be null
at cz.creeperface.nukkit.gac.e.onRun(Unknown Source) ~[?:?]
at cn.nukkit.scheduler.Task.run(Task.java:51) ~[server.jar:?]
at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) [server.jar:?]
at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296) [server.jar:?]
at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1369) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:1144) [server.jar:?]
at cn.nukkit.Server.start(Server.java:1104) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:760) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]
