### ISSUE TITLE
[ERROR] Could not tick level "world": java.lang.NullPointerException

### ISSUE THREAD

**Issue by DenzelCode** [PowerNukkit/PowerNukkit#638]
# 🐞 I found a bug

### 📋 Debug information
* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT
* Debug link: https://debugpaste.powernukkit.org/pastes/honitumoxe

### 💢 Crash Dump, Stack Trace and Other Files

```java
2020-09-23 08:21:17.158 [main] ERROR - Could not tick level "world": java.lang.NullPointerException
        at cn.nukkit.level.Level.getChunk(Level.java:2818)
        at cn.nukkit.level.Level.getChunk(Level.java:2813)
        at cn.nukkit.level.Level.getBlock(Level.java:1655)
        at cn.nukkit.level.Level.getBlock(Level.java:1640)
        at cn.nukkit.level.Level.getBlock(Level.java:1624)
        at cn.nukkit.level.Position.getLevelBlockAtLayer(Position.java:140)
        at cn.nukkit.Player.checkBlockCollision(Player.java:1477)
        at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:1444)
        at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:236)
        at cn.nukkit.Player.entityBaseTick(Player.java:1908)
        at cn.nukkit.Player.onUpdate(Player.java:1807)
        at cn.nukkit.level.Level.doTick(Level.java:902)
        at cn.nukkit.Server.checkTickUpdates(Server.java:1273)
        at cn.nukkit.Server.tick(Server.java:1355)
        at cn.nukkit.Server.tickProcessor(Server.java:1127)
        at cn.nukkit.Server.start(Server.java:1095)
        at cn.nukkit.Server.<init>(Server.java:751)
        at cn.nukkit.Nukkit.main(Nukkit.java:120)
```

**Comment by joserobjr** [comment]
Thank you for the report, the issue should be fixed now. I identified that in your server, some unloaded levels were trying to tick. #634 patched this issue
