### ISSUE TITLE
Bug on level

### ISSUE THREAD

**Issue by DenzelCode** [PowerNukkit/PowerNukkit#639]
# 🐞 I found a bug
java.lang.RuntimeException: java.lang.NumberFormatException: For input string: ""
        at cn.nukkit.level.generator.Flat.parsePreset(Flat.java:144)
        at cn.nukkit.level.generator.Flat.generateChunk(Flat.java:159)
        at cn.nukkit.level.generator.task.PopulationTask.generationTask(PopulationTask.java:103)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:48)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:43)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:662)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at cn.nukkit.level.generator.Flat.parsePreset(Flat.java:91)

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT
* Debug link: https://hastebin.com/inojigixic
* Timings link (if relevant): ✍

**Comment by RORIdev** [comment]
Related to #638. Possibly a duplicate. This one has more details about what causes the NPE. Closing #638 for being a duplicate should be considered.

**Comment by DenzelCode** [comment]
It is not related to it... they are different errors and they occur on different times.

**Comment by joserobjr** [comment]
Hi @DenzelCode , thank you for the report. What was the preset used to generate the world?

**Comment by DenzelCode** [comment]
> Hi @DenzelCode , thank you for the report. What was the preset used to generate the world?

FLAT
