### ISSUE TITLE
crash server connect

### ISSUE THREAD

**Issue by davee261** [PowerNukkit/PowerNukkit#650]
[crash server.txt](https://github.com/PowerNukkit/PowerNukkit/files/5306060/crash.server.txt)

https://github.com/PowerNukkit/PowerNukkit/actions/runs/277830608 (at 4491be1)

I downloaded this I thought it was version 1.4.0.0 or nwm where to download it I connected to the server and the whole server crashed

**Comment by joserobjr** [comment]
Something is doing an infinite or uncontained recursive indirect loop
```java
t cn.nukkit.level.Level.setBlock(Level.java:2011) ~[server.jar:?]
at cn.nukkit.level.Level.getBlock(Level.java:1713) ~[server.jar:?]
at cn.nukkit.level.Level.getBlock(Level.java:1683) ~[server.jar:?]
at cn.nukkit.block.Block.getSideAtLayer(Block.java:1440) ~[server.jar:?]
at cn.nukkit.level.Level.updateAround(Level.java:1375) ~[server.jar:?]
at cn.nukkit.level.Level.updateAround(Level.java:1382) ~[server.jar:?]
at cn.nukkit.level.Level.setBlock(Level.java:2011) ~[server.jar:?]
at cn.nukkit.level.Level.getBlock(Level.java:1713) ~[server.jar:?]
at cn.nukkit.level.Level.getBlock(Level.java:1683) ~[server.jar:?]
at cn.nukkit.block.Block.getSideAtLayer(Block.java:1440) ~[server.jar:?]
at cn.nukkit.level.Level.updateAround(Level.java:1375) ~[server.jar:?]
at cn.nukkit.level.Level.updateAround(Level.java:1382) ~[server.jar:?]
at cn.nukkit.level.Level.setBlock(Level.java:2011) ~[server.jar:?]
at cn.nukkit.level.Level.getBlock(Level.java:1713) ~[server.jar:?]
at cn.nukkit.level.Level.getBlock(Level.java:1683) ~[server.jar:?]
at cn.nukkit.block.Block.getSideAtLayer(Block.java:1440) ~[server.jar:?]
at cn.nukkit.level.Level.updateAround(Level.java:1375) ~[server.jar:?]
at cn.nukkit.level.Level.updateAround(Level.java:1382) ~[server.jar:?]
at cn.nukkit.level.Level.setBlock(Level.java:2011) ~[server.jar:?]
at cn.nukkit.level.Level.getBlock(Level.java:1713) ~[server.jar:?]
at cn.nukkit.level.Level.getBlock(Level.java:1683) ~[server.jar:?]
at cn.nukkit.block.Block.getSideAtLayer(Block.java:1440) ~[server.jar:?]
at cn.nukkit.level.Level.updateAround(Level.java:1375) ~[server.jar:?]
at cn.nukkit.level.Level.updateAround(Level.java:1382) ~[server.jar:?]
at cn.nukkit.level.Level.setBlock(Level.java:2011) ~[server.jar:?]
at cn.nukkit.level.Level.getBlock(Level.java:1713) ~[server.jar:?]
at cn.nukkit.level.Level.getBlock(Level.java:1683) ~[server.jar:?]
at cn.nukkit.block.Block.getSideAtLayer(Block.java:1440) ~[server.jar:?]
at cn.nukkit.level.Level.updateAround(Level.java:1375) ~[server.jar:?]
at cn.nukkit.level.Level.updateAround(Level.java:1382) ~[server.jar:?]
at cn.nukkit.level.Level.setBlock(Level.java:2011) ~[server.jar:?]
```

**Comment by davee261** [comment]
> Něco dělá nekonečnou nebo neomezenou rekurzivní nepřímou smyčku
> 
> ```java
> t cn.nukkit.level . Úroveň . setBlock ( úroveň . java : 2011 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . getBlock ( úroveň . java : 1713 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . getBlock ( úroveň . java : 1683 ) ~ [server . jar :? ]
> na cn.nukkit.block . Blokovat . getSideAtLayer ( blok . java : 1440 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . updateAround ( úroveň . java : 1375 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . updateAround ( úroveň . java : 1382 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . setBlock ( úroveň . java : 2011 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . getBlock ( úroveň . java : 1713 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . getBlock ( úroveň . java : 1683 ) ~ [server . jar :? ]
> na cn.nukkit.block . Blokovat . getSideAtLayer ( blok . java : 1440 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . updateAround ( úroveň . java : 1375 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . updateAround ( úroveň . java : 1382 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . setBlock ( úroveň . java : 2011 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . getBlock ( úroveň . java : 1713 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . getBlock ( úroveň . java : 1683 ) ~ [server . jar :? ]
> na cn.nukkit.block . Blokovat . getSideAtLayer ( blok . java : 1440 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . updateAround ( úroveň . java : 1375 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . updateAround ( úroveň . java : 1382 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . setBlock ( úroveň . java : 2011 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . getBlock ( úroveň . java : 1713 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . getBlock ( úroveň . java : 1683 ) ~ [server . jar :? ]
> na cn.nukkit.block . Blokovat . getSideAtLayer ( blok . java : 1440 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . updateAround ( úroveň . java : 1375 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . updateAround ( úroveň . java : 1382 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . setBlock ( úroveň . java : 2011 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . getBlock ( úroveň . java : 1713 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . getBlock ( úroveň . java : 1683 ) ~ [server . jar :? ]
> na cn.nukkit.block . Blokovat . getSideAtLayer ( blok . java : 1440 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . updateAround ( úroveň . java : 1375 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . updateAround ( úroveň . java : 1382 ) ~ [server . jar :? ]
> na úrovni cn.nukkit . Úroveň . setBlock ( úroveň . java : 2011 ) ~ [server . jar :? ]
> ```

I gave the latest version of nwm if I downloaded it correctly but I connected to the server for the first time and I saw the world and the whole server crashed

**Comment by joserobjr** [comment]
Can you share the whole log file? You can send it privately by discord if you prefer. There's a block with invalid state being repaired and it is causing other blocks to be repaired too, the full log might be saying which block is causing all the trouble. I'm going to push a commit that will disable block updates when a block is repaired, which might help the crashing issue but it won't fix the root cause.
