### ISSUE TITLE
Tick Error - Negative BigIntegers are not supported (nearly infinite bits)

### ISSUE THREAD

**Issue by good777LUCKY** [PowerNukkit/PowerNukkit#709]
# 🐞 I found a bug

### ▶ Steps to Reproduce

Unknown.

### ✔ Expected Behavior

Chunk should load properly and able to join server.

### ❌ Actual Behavior

Chunk will not load properly and when you join server near to corrupted chunk, you can't join the server.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-SNAPSHOT (0d54f0b8774445b1ae314d50b0237aae67f1f3f4)
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

```
ERROR - nukkit.level.tickError
java.lang.UnsupportedOperationException: Negative BigIntegers are not supported (nearly infinite bits)
	at cn.nukkit.math.NukkitMath.bitLength(NukkitMath.java:156) ~[powernukkit.jar:?]
	at cn.nukkit.blockstate.IMutableBlockState.repairStorage(IMutableBlockState.java:217) ~[powernukkit.jar:?]
	at cn.nukkit.blockstate.IMutableBlockState.setDataStorage(IMutableBlockState.java:103) ~[powernukkit.jar:?]
	at cn.nukkit.block.Block.setDataStorage(Block.java:1945) ~[powernukkit.jar:?]
	at cn.nukkit.blockstate.IBlockState.getBlock(IBlockState.java:269) ~[powernukkit.jar:?]
	at cn.nukkit.blockstate.BlockState.getBlock(BlockState.java:499) ~[powernukkit.jar:?]
	at cn.nukkit.blockstate.IBlockState.getBlockRepairing(IBlockState.java:374) ~[powernukkit.jar:?]
	at cn.nukkit.blockstate.IBlockState.getBlockRepairing(IBlockState.java:353) ~[powernukkit.jar:?]
	at cn.nukkit.level.Level.getBlock(Level.java:1721) ~[powernukkit.jar:?]
	at cn.nukkit.level.Level.getBlock(Level.java:1676) ~[powernukkit.jar:?]
	at cn.nukkit.level.Level.getBlock(Level.java:1672) ~[powernukkit.jar:?]
	at cn.nukkit.level.Level.getCollisionBlocks(Level.java:1476) ~[powernukkit.jar:?]
	at cn.nukkit.entity.Entity.checkBlockCollision(Entity.java:2305) ~[powernukkit.jar:?]
	at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:1449) ~[powernukkit.jar:?]
	at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:237) ~[powernukkit.jar:?]
	at nukkitcoders.mobplugin.entities.BaseEntity.entityBaseTick(BaseEntity.java:152) ~[MobPlugin-1.16.3.jar:?]
	at nukkitcoders.mobplugin.entities.monster.walking.Spider.entityBaseTick(Spider.java:179) ~[MobPlugin-1.16.3.jar:?]
	at nukkitcoders.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:154) ~[MobPlugin-1.16.3.jar:?]
	at cn.nukkit.level.Level.doTick(Level.java:932) ~[powernukkit.jar:?]
	at cn.nukkit.Server.checkTickUpdates(Server.java:1290) [powernukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1372) [powernukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1144) [powernukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1104) [powernukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:760) [powernukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:120) [powernukkit.jar:?]
```

### 💬 Anything else we should know?

-

**Comment by good777LUCKY** [comment]
This log was printed before tick error, `ERROR - Found an unknown BlockId:Meta combination: 474:-1 - minecraft:beehive;nukkit-legacy=-1 - BlockProperties{bitSize=5, properties=[0-2:direction, 2-5:honey_level]} - minecraft:beehive, trying to repair or replacing with an "UPDATE!" block.`

**Comment by joserobjr** [comment]
Hi, please check if it still happens after this merge: https://github.com/PowerNukkit/PowerNukkit/pull/698

If it does happen, please send the new error log even if it looks the same

**Comment by good777LUCKY** [comment]
> Hi, please check if it still happens after this merge: #698
> 
> If it does happen, please send the new error log even if it looks the same

It is fixed, thank you!
