### ISSUE TITLE
GAC Compatibility Issue

### ISSUE THREAD

**Issue by RealTriassic** [PowerNukkit/PowerNukkit#719]
# 🔌 Plugin compatibility issue

### ▶ Steps to Reproduce
1. Get the latest version of GAC.
2. Deop yourself on the server.
3. Start walking around, using elytra and other actions that would trigger MovePlayerPacket.

### ✔ Expected Behavior
No errors from GAC in console, it should just work.

### ❌ Actual Behavior
Console gets spammed with the error i sent above, sometimes freezing the server for 20 seconds and making everyone time out. (Though im not sure about the freezing being caused by GAC).

### 📋 Debug information
* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT
* Debug link: https://debugpaste.powernukkit.org/pastes/uxozuwoboj

**Comment by RealTriassic** [comment]
Oops, seems like the error didn't go into the issue report, but here it is:


12:23:18 [WARN ] Error whilst processing the packet 19:MovePlayerPacket for USER (full data: MovePlayerPacket(eid=1808, x=20275.549, y=83.62, z=394.9031, yaw=-16.772888, headYaw=343.2271, pitch=32.036865, mode=0, onGround=true, ridingEid=0, int1=0, int2=0))
--
2 | java.lang.NullPointerException: null

**Comment by RealTriassic** [comment]
Hold on, i got a larger error:

13:32:58 [WARN ] Error whilst processing the packet 19:MovePlayerPacket for USER (full data: MovePlayerPacket(eid=211, x=203807.38, y=89.62, z=-675.098, yaw=27.645935, headYaw=27.645935, pitch=15.188461, mode=0, onGround=true, ridingEid=0, int1=0, int2=0))
java.lang.NullPointerException: null
at cn.nukkit.Player.sendPosition(Player.java:4632) ~[server.jar:?]
at cn.nukkit.Player.sendPosition(Player.java:4626) ~[server.jar:?]
at cz.creeperface.nukkit.gac.X.a(Unknown Source) ~[?:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
at cn.nukkit.network.Network.lambda$processPackets$3(Network.java:285) ~[server.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1259) [?:1.8.0_262]
at cn.nukkit.network.Network.processPackets(Network.java:283) [server.jar:?]
at cn.nukkit.network.Network.processBatch(Network.java:269) [server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:2303) [server.jar:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) [GAC-1.0.jar:?]
at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:75) [server.jar:?]
at cz.creeperface.nukkit.gac.V.process(Unknown Source) [GAC-1.0.jar:?]
at cn.nukkit.network.Network.processInterfaces(Network.java:158) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1361) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:1144) [server.jar:?]
at cn.nukkit.Server.start(Server.java:1104) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:760) [server.jar:?]

**Comment by RealTriassic** [comment]
also this:

07:26:16 [FATAL] Exception while invoking run
java.lang.NullPointerException: cheatData.lastPos.getLevel() must not be null
at cz.creeperface.nukkit.gac.e.onRun(Unknown Source) ~[?:?]
at cn.nukkit.scheduler.Task.run(Task.java:51) ~[server.jar:?]
at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) [server.jar:?]
at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296) [server.jar:?]
at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1369) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:1144) [server.jar:?]
at cn.nukkit.Server.start(Server.java:1104) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:760) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]

**Comment by RealTriassic** [comment]
I have come to the conclusion that this error is the same as: https://github.com/PowerNukkit/PowerNukkit/issues/530
