### ISSUE TITLE
InventoryTransactionPacket error

### ISSUE THREAD

**Issue by RealTriassic** [PowerNukkit/PowerNukkit#730]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Place a redstone repeater on the floor
2. Change the delay to 4 ticks
3. Try changing the delay one more time (back to 1)

### ✔ Expected Behavior

No errors in console, everything should work.

### ❌ Actual Behavior

21:09:57 [WARN ] Error whilst processing the packet 30:InventoryTransactionPacket for USER (full data: InventoryTransactionPacket(transactionType=2, actions=[], transactionData=UseItemData(actionType=0, blockPos=BlockPosition(level=,x=148156,y=15,z=154427), face=up, hotbarSlot=5, itemInHand=Item Air (0:0)x0, playerPos=Vector3(x=148156.265625,y=18.6200008392334,z=154427.0625), clickPos=Vector3(x=0.2188,y=0.125,z=0.3438), blockRuntimeId=637), hasNetworkIds=false, legacyRequestId=0, isCraftingPart=false, isEnchantingPart=false))
cn.nukkit.blockstate.exception.InvalidBlockStateException: The block state BlockState(blockId=93, storage=18) is invalid: The state have more data bits than specified in the properties. Bits: 5, Max: 4
BlockProperties{bitSize=4, properties=[0-4:nukkit-legacy]}
at cn.nukkit.blockstate.ByteMutableBlockState.validate(ByteMutableBlockState.java:158) ~[server.jar:?]
at cn.nukkit.blockstate.ByteMutableBlockState.setDataStorageFromInt(ByteMutableBlockState.java:125) ~[server.jar:?]
at cn.nukkit.block.Block.setDamage(Block.java:1174) ~[server.jar:?]
at cn.nukkit.block.BlockRedstoneRepeaterUnpowered.onActivate(BlockRedstoneRepeaterUnpowered.java:37) ~[server.jar:?]
at cn.nukkit.level.Level.useItemOn(Level.java:2433) ~[server.jar:?]
at cn.nukkit.level.Level.useItemOn(Level.java:2390) ~[server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:3409) ~[server.jar:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(NukkitCheatPlayer.kt:74) ~[?:?]
at cn.nukkit.network.Network.lambda$processPackets$3(Network.java:285) ~[server.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1259) [?:1.8.0_262]
at cn.nukkit.network.Network.processPackets(Network.java:283) [server.jar:?]
at cn.nukkit.network.Network.processBatch(Network.java:269) [server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:2303) [server.jar:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(NukkitCheatPlayer.kt:74) [GAC-1.0.jar:?]
at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:75) [server.jar:?]
at cz.creeperface.nukkit.gac.V.process(GACNetworkInterface.kt) [GAC-1.0.jar:?]
at cn.nukkit.network.Network.processInterfaces(Network.java:158) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1361) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:1144) [server.jar:?]
at cn.nukkit.Server.start(Server.java:1104) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:760) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]

**Comment by RealTriassic** [comment]
https://hastebin.com/lejoquzosu

**Comment by RealTriassic** [comment]
That's the debugpaste ^
