### ISSUE TITLE
World Loading Issue on Startup

### ISSUE THREAD

**Issue by MrRazamataz** [PowerNukkit/PowerNukkit#765]
```java
18:39:37 [ERROR] nukkit.level.loadError
cn.nukkit.utils.LevelException: Constructor of class cn.nukkit.level.format.anvil.Anvil failed
        at cn.nukkit.level.Level.lambda$new$1(Level.java:314) ~[server.jar:?]
        at cn.nukkit.level.Level.<init>(Level.java:333) ~[server.jar:?]
        at cn.nukkit.level.Level.<init>(Level.java:302) ~[server.jar:?]
        at cn.nukkit.Server.loadLevel(Server.java:2136) [server.jar:?]
        at cn.nukkit.level.EnumLevel.initLevels(EnumLevel.java:23) [server.jar:?]
        at cn.nukkit.Server.<init>(Server.java:746) [server.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_272]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_272]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_272]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_272]
        at cn.nukkit.level.Level.lambda$new$1(Level.java:312) ~[server.jar:?]
        ... 6 more
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240) ~[?:1.8.0_272]
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_272]
        at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117) ~[?:1.8.0_272]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_272]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[?:1.8.0_272]
        at java.io.DataInputStream.readByte(DataInputStream.java:265) ~[?:1.8.0_272]
        at cn.nukkit.nbt.stream.NBTInputStream.readByte(NBTInputStream.java:64) ~[server.jar:?]
        at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:91) ~[server.jar:?]
        at cn.nukkit.nbt.NBTIO.read(NBTIO.java:93) ~[server.jar:?]
        at cn.nukkit.nbt.NBTIO.read(NBTIO.java:89) ~[server.jar:?]
        at cn.nukkit.nbt.NBTIO.readCompressed(NBTIO.java:127) ~[server.jar:?]
        at cn.nukkit.level.format.generic.BaseLevelProvider.<init>(BaseLevelProvider.java:58) ~[server.jar:?]
        at cn.nukkit.level.format.anvil.Anvil.<init>(Anvil.java:41) ~[server.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_272]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_272]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_272]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_272]
        at cn.nukkit.level.Level.lambda$new$1(Level.java:312) ~[server.jar:?]
        ... 6 more
18:39:37 [INFO ] No level called "nether" found, creating default nether level.
18:39:37 [ERROR] nukkit.level.loadError
cn.nukkit.utils.LevelException: Constructor of class cn.nukkit.level.format.anvil.Anvil failed
        at cn.nukkit.level.Level.lambda$new$1(Level.java:314) ~[server.jar:?]
        at cn.nukkit.level.Level.<init>(Level.java:333) ~[server.jar:?]
        at cn.nukkit.level.Level.<init>(Level.java:302) ~[server.jar:?]
        at cn.nukkit.Server.loadLevel(Server.java:2136) [server.jar:?]
        at cn.nukkit.level.EnumLevel.initLevels(EnumLevel.java:37) [server.jar:?]
        at cn.nukkit.Server.<init>(Server.java:746) [server.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_272]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_272]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_272]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_272]
        at cn.nukkit.level.Level.lambda$new$1(Level.java:312) ~[server.jar:?]
        ... 6 more
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240) ~[?:1.8.0_272]
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_272]
        at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117) ~[?:1.8.0_272]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_272]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[?:1.8.0_272]
        at java.io.DataInputStream.readByte(DataInputStream.java:265) ~[?:1.8.0_272]
        at cn.nukkit.nbt.stream.NBTInputStream.readByte(NBTInputStream.java:64) ~[server.jar:?]
        at cn.nukkit.nbt.tag.Tag.readNamedTag(Tag.java:91) ~[server.jar:?]
        at cn.nukkit.nbt.NBTIO.read(NBTIO.java:93) ~[server.jar:?]
        at cn.nukkit.nbt.NBTIO.read(NBTIO.java:89) ~[server.jar:?]
        at cn.nukkit.nbt.NBTIO.readCompressed(NBTIO.java:127) ~[server.jar:?]
        at cn.nukkit.level.format.generic.BaseLevelProvider.<init>(BaseLevelProvider.java:58) ~[server.jar:?]
        at cn.nukkit.level.format.anvil.Anvil.<init>(Anvil.java:41) ~[server.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_272]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_272]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_272]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_272]
        at cn.nukkit.level.Level.lambda$new$1(Level.java:312) ~[server.jar:?]
        ... 6 more
18:39:37 [WARN ] No level called "nether" found or nether is disabled in server properties! Nether functionality will be disabled.
```

**Comment by joserobjr** [comment]
Your level.dat file has corrupted, you will have to recover it from a backup. I'm going to improve the way it saves and load to prevent corruptions like this in case it fails to save.

**Comment by MrRazamataz** [comment]
Is level.dat just gamerules?
Like can I delete it and put the gamerules back?

**Comment by joserobjr** [comment]
It holds the world seed, generator settings, gamerules, spawn location and a few details.

![image](https://user-images.githubusercontent.com/3679022/99915630-8bd32100-2ce3-11eb-88f8-c479d4bd9e2c.png)
