### ISSUE TITLE
When in creative and your inventory is full, you can pick up blocks and items that you don't have in your inventory so they disappear. 

### ISSUE THREAD

**Issue by MrRazamataz** [PowerNukkit/PowerNukkit#802]
https://youtu.be/o8kC1koZoec

**Comment by MonoAdrian23** [comment]
3 Issues and no /debugpaste 
Please use /debugpaste

**Comment by MrRazamataz** [comment]
> debugpaste=> 01:52:50 [INFO ] [Player] <DressierPen9301> he wants to be a member of my kingdom
> debugpaste=> 01:53:02 [FATAL] Exception in asynchronous task
java.lang.NullPointerException: null
at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator.nextEntry(Long2ObjectOpenHashMap.java:669) ~[server.jar:?]
at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$ValueIterator.next(Long2ObjectOpenHashMap.java:951) ~[server.jar:?]
at java.util.AbstractCollection.toArray(AbstractCollection.java:196) ~[?:1.8.0_262]
at cn.nukkit.level.Level.getEntities(Level.java:2619) ~[server.jar:?]
at cn.nukkit.command.defaults.StatusCommand.execute(StatusCommand.java:93) ~[server.jar:?]
at cn.nukkit.command.defaults.DebugPasteCommand$1.onRun(DebugPasteCommand.java:38) ~[server.jar:?]
at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) ~[server.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
> java.lang.NullPointerException
at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator.nextEntry(Long2ObjectOpenHashMap.java:669)
at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$ValueIterator.next(Long2ObjectOpenHashMap.java:951)
at java.util.AbstractCollection.toArray(AbstractCollection.java:196)
at cn.nukkit.level.Level.getEntities(Level.java:2619)
at cn.nukkit.command.defaults.StatusCommand.execute(StatusCommand.java:93)
at cn.nukkit.command.defaults.DebugPasteCommand$1.onRun(DebugPasteCommand.java:38)
at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
01:53:02 [INFO ] [BugReport] An error has been detected, creating a bug report.
> 01:53:02 [INFO ] [BugReport] A bug report has been created: /home/container/logs/bug_reports/20201204015302_NullPointerException.md
> 01:53:02 [INFO ] [Player] <DressierPen9301> who wants to join my kingdom
> 01:53:07 [INFO ] [Staff] <ItzBlue72> I'm not looking to join a kingdom rn. Sorry
> 01:53:10 [ERROR] Throwing
java.io.IOException: Server returned HTTP response code: 503 for URL: https://hastebin.com/documents
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900) ~[?:1.8.0_262]
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[?:1.8.0_262]
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_262]
at cn.nukkit.utils.HastebinUtility.upload(HastebinUtility.java:30) ~[server.jar:?]
at cn.nukkit.command.defaults.DebugPasteCommand$1.onRun(DebugPasteCommand.java:40) [server.jar:?]
at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) [server.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
> about=> 01:53:22 [INFO ] [Staff] <CassiaFleur> we have plugins like /rtp which tps you to a random place
> 01:53:22 [INFO ] This server is running Nukkit 1.4.0.0-PN-ALPHA.2-SNAPSHOT (git-1f343fc) 「PowerNukkit」 implementing API version 1.0.11 for Minecraft: BE v1.16.100 (protocol version 419)

**Comment by MrRazamataz** [comment]
Debugpaste doesn't work

**Comment by MrRazamataz** [comment]
(git-1f343fc)

**Comment by RORIdev** [comment]
DVB.

**Comment by MrRazamataz** [comment]
This is wierd, I didnt know this was a "feature" in vanilla, seems like a dumb idea.
