### ISSUE TITLE
Compatabilty with "MyGuardian" Anticheat

### ISSUE THREAD

**Issue by MrRazamataz** [PowerNukkit/PowerNukkit#819]
**Plugin link:** [https://cloudburstmc.org/resources/myguardian-anticheat.465/](Link)

19:18:44 [FATAL] Could not pass event "cn.nukkit.event.player.PlayerMoveEvent" to "MyGuardian v1.0": null on fr.albanw.myguardian.listeners.Move
19:18:44 [ERROR] Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:33) ~[server.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[server.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:577) [server.jar:?]
        at cn.nukkit.Player.processMovement(Player.java:1629) [server.jar:?]
        at cn.nukkit.Player.onUpdate(Player.java:1826) [server.jar:?]
        at cn.nukkit.level.Level.doTick(Level.java:943) [server.jar:?]
        at cn.nukkit.Server.checkTickUpdates(Server.java:1288) [server.jar:?]
        at cn.nukkit.Server.tick(Server.java:1370) [server.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1142) [server.jar:?]
        at cn.nukkit.Server.start(Server.java:1102) [server.jar:?]
        at cn.nukkit.Server.<init>(Server.java:762) [server.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]
Caused by: java.lang.NullPointerException
        at fr.albanw.myguardian.listeners.Move.onMove(Move.java:20) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:28) ~[server.jar:?]
        ... 11 more
19:18:44 [FATAL] Could not pass event "cn.nukkit.event.player.PlayerMoveEvent" to "MyGuardian v1.0": null on fr.albanw.myguardian.listeners.Move
19:18:44 [ERROR] Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:33) ~[server.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[server.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:577) [server.jar:?]
        at cn.nukkit.Player.processMovement(Player.java:1629) [server.jar:?]
        at cn.nukkit.Player.onUpdate(Player.java:1826) [server.jar:?]
        at cn.nukkit.level.Level.doTick(Level.java:943) [server.jar:?]
        at cn.nukkit.Server.checkTickUpdates(Server.java:1288) [server.jar:?]
        at cn.nukkit.Server.tick(Server.java:1370) [server.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1142) [server.jar:?]
        at cn.nukkit.Server.start(Server.java:1102) [server.jar:?]
        at cn.nukkit.Server.<init>(Server.java:762) [server.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]
Caused by: java.lang.NullPointerException
        at fr.albanw.myguardian.listeners.Move.onMove(Move.java:20) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:28) ~[server.jar:?]
        ... 11 more

**Comment by MrRazamataz** [comment]
git-475659c

**Comment by MrRazamataz** [comment]
> Hey @MrRazamataz, thank you for the report!
> 
> ⚠️ **I could not find which PowerNukkit version you are using from your message.** ⚠️
> 
> Please, run the command: `/debugpaste` it will generate a link, send us this link replying this issue.
> It's an important step to get your issue resolved.
> 
> Don't say _latest_ or _current version_, we support different versions and your latest may not be the same latest as our, and your latest will not be the same latest in the future, so please, use a fixed version.
> 
> Thank you 👍

https://hastebin.com/ulolizujoc

**Comment by MrRazamataz** [comment]
After server restart and after a few days it seems to be fine.
