### ISSUE TITLE
Player can't join if blockData: Negative value is not allowed: -1 error occurs

### ISSUE THREAD

**Issue by good777LUCKY** [PowerNukkit/PowerNukkit#860]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Start the server
2. Join the server
3. Client cannot connect to server

### ✔ Expected Behavior

Client can connect the server even error occurred

### ❌ Actual Behavior

Can't join the server

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-SNAPSHOT (b00df76)
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

```
2020-12-24 09:23:27.690 [main] WARN  - Error whilst processing the packet 1:LoginPacket for <Player Name> (full data: LoginPacket(username=<Player Name>, protocol=422, clientUUID=3bd00788-7bc2-3f60-ac26-c8d6265df3e8, clientId=-3064339040336619856, skin=Skin(fullSkinId=cd1d7fdb-417e-46b9-8c60-ad6b9777f377, skinId=73767aa6-5949-4529-947f-2fcdbc94c2cb.Earth, skinResourcePatch={
   "geometry" : {
      "default" : "geometry.EarthSkin.earth"
   }
}
, skinData=SerializedImage(width=64, height=64), animations=[], personaPieces=[], tintColors=[], capeData=SerializedImage(width=64, height=32), premium=true, persona=false, capeOnClassic=true, capeId=1b99b12c-3caa-4ccb-8f79-f79f053e586f, skinColor=#0, armSize=, trusted=false)))
java.lang.IllegalArgumentException: blockData: Negative value is not allowed: -1
	at cn.nukkit.utils.Validation.checkPositive(Validation.java:75) ~[powernukkit.jar:?]
	at cn.nukkit.blockstate.BlockState.of(BlockState.java:103) ~[powernukkit.jar:?]
	at cn.nukkit.blockstate.BlockState.withData(BlockState.java:219) ~[powernukkit.jar:?]
	at cn.nukkit.level.format.updater.BeehiveUpdater.update(BeehiveUpdater.java:39) ~[powernukkit.jar:?]
	at cn.nukkit.level.format.updater.GroupedUpdaters.update(GroupedUpdaters.java:15) ~[powernukkit.jar:?]
	at cn.nukkit.level.format.updater.ChunkUpdater.walk(ChunkUpdater.java:130) ~[powernukkit.jar:?]
	at cn.nukkit.level.format.updater.ChunkUpdater.updateToV8FromV0toV5(ChunkUpdater.java:91) ~[powernukkit.jar:?]
	at cn.nukkit.level.format.updater.ChunkUpdater.backwardCompatibilityUpdate(ChunkUpdater.java:47) ~[powernukkit.jar:?]
	at cn.nukkit.level.format.generic.BaseChunk.backwardCompatibilityUpdate(BaseChunk.java:53) ~[powernukkit.jar:?]
	at cn.nukkit.level.Level.forceLoadChunk(Level.java:3271) ~[powernukkit.jar:?]
	at cn.nukkit.level.Level.getChunk(Level.java:2912) ~[powernukkit.jar:?]
	at cn.nukkit.Player.processLogin(Player.java:2161) ~[powernukkit.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2424) ~[powernukkit.jar:?]
	at cn.nukkit.network.Network.lambda$processPackets$3(Network.java:293) ~[powernukkit.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) [?:1.8.0_275]
	at cn.nukkit.network.Network.processPackets(Network.java:291) [powernukkit.jar:?]
	at cn.nukkit.network.Network.processBatch(Network.java:277) [powernukkit.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2288) [powernukkit.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:75) [powernukkit.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:166) [powernukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1366) [powernukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1142) [powernukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1102) [powernukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:762) [powernukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:120) [powernukkit.jar:?]
2020-12-24 09:23:35.641 [main] INFO  - §b<Player Name>§f[/<Address:Port>]이(가) Disconnected from Server
```

**Comment by GoodLucky777** [comment]
In e2149a5,
```
[main] ERROR - An error occurred whilst handling LoginPacket for <Player Name>
java.lang.IllegalArgumentException: blockData: Negative value is not allowed: -1
	at cn.nukkit.utils.Validation.checkPositive(Validation.java:75) ~[powernukkit.jar:?]
	at cn.nukkit.blockstate.BlockState.of(BlockState.java:103) ~[powernukkit.jar:?]
	at cn.nukkit.blockstate.BlockState.withData(BlockState.java:219) ~[powernukkit.jar:?]
	at cn.nukkit.level.format.updater.BeehiveUpdater.update(BeehiveUpdater.java:39) ~[powernukkit.jar:?]
	at cn.nukkit.level.format.updater.GroupedUpdaters.update(GroupedUpdaters.java:15) ~[powernukkit.jar:?]
	at cn.nukkit.level.format.updater.ChunkUpdater.walk(ChunkUpdater.java:130) ~[powernukkit.jar:?]
	at cn.nukkit.level.format.updater.ChunkUpdater.updateToV8FromV0toV5(ChunkUpdater.java:91) ~[powernukkit.jar:?]
	at cn.nukkit.level.format.updater.ChunkUpdater.backwardCompatibilityUpdate(ChunkUpdater.java:47) ~[powernukkit.jar:?]
	at cn.nukkit.level.format.generic.BaseChunk.backwardCompatibilityUpdate(BaseChunk.java:53) ~[powernukkit.jar:?]
	at cn.nukkit.level.Level.forceLoadChunk(Level.java:3253) ~[powernukkit.jar:?]
	at cn.nukkit.level.Level.getChunk(Level.java:2894) ~[powernukkit.jar:?]
	at cn.nukkit.Player.processLogin(Player.java:2151) ~[powernukkit.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2414) ~[powernukkit.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:122) [powernukkit.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:170) [powernukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1356) [powernukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1131) [powernukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1091) [powernukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:763) [powernukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:120) [powernukkit.jar:?]
```
