### ISSUE TITLE
Unknown item mapping Item Unknown (879:3)

### ISSUE THREAD

**Issue by GoodLucky777** [PowerNukkit/PowerNukkit#960]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Use PowerNukkit 1.4 that use new item ids.
2. Update to PowerNukkit 1.4 that use RuntimeItemMapping
3. Some items will make errors, player can't join the server if the player have it.

### ✔ Expected Behavior

No error and no joining problem

### ❌ Actual Behavior

RuntimeItem error occurs and the player can't join.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT (38df99d5ecc8d6fac637227dcf8d9a3197278afc)
* Debug link: -
* Timings link (if relevant): -

### 💢 Crash Dump, Stack Trace and Other Files

```
2021-02-03 14:46:14.717 [main] ERROR - A RuntimeException happened while ticking the server
java.lang.IllegalArgumentException: Unknown item mapping Item Unknown (879:3)x12
	at cn.nukkit.item.RuntimeItemMapping.getNetworkFullId(RuntimeItemMapping.java:81) ~[powernukkit.jar:?]
	at cn.nukkit.utils.BinaryStream.putSlot(BinaryStream.java:472) ~[powernukkit.jar:?]
	at cn.nukkit.network.protocol.InventoryContentPacket.encode(InventoryContentPacket.java:46) ~[powernukkit.jar:?]
	at cn.nukkit.network.protocol.DataPacket.tryEncode(DataPacket.java:29) ~[powernukkit.jar:?]
	at cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:219) ~[powernukkit.jar:?]
	at cn.nukkit.Player.dataPacket(Player.java:1134) ~[powernukkit.jar:?]
	at cn.nukkit.inventory.PlayerInventory.sendContents(PlayerInventory.java:439) ~[powernukkit.jar:?]
	at cn.nukkit.inventory.PlayerInventory.sendContents(PlayerInventory.java:409) ~[powernukkit.jar:?]
	at cn.nukkit.Player.doFirstSpawn(Player.java:896) ~[powernukkit.jar:?]
	at cn.nukkit.Player.sendNextChunk(Player.java:888) ~[powernukkit.jar:?]
	at cn.nukkit.Player.checkNetwork(Player.java:2013) ~[powernukkit.jar:?]
	at cn.nukkit.Server.tick(Server.java:1370) ~[powernukkit.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1132) [powernukkit.jar:?]
	at cn.nukkit.Server.start(Server.java:1092) [powernukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:764) [powernukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:192) [powernukkit.jar:?]
```

### 💬 Anything else we should know?

-

**Comment by joserobjr** [comment]
Thank you for reporting!
