### ISSUE TITLE
GAC not loading on latest bleeding.

### ISSUE THREAD

**Issue by RealTriassic** [PowerNukkit/PowerNukkit#963]
GAC does not work on the latest commit on bleeding as we get this error when loading:

06:31:16 [INFO ] Loading GAC v1.3.8
06:31:17 [FATAL] Could not load plugin
java.lang.NullPointerException: null
at cz.creeperface.nukkit.gac.aq.a(Reflect.kt:1036) ~[?:?]
at cz.creeperface.nukkit.gac.V.<init>(GACNetworkInterface.kt:30) ~[?:?]
at cz.creeperface.nukkit.gac.am.a(Hacks.kt:21) ~[?:?]
at cz.creeperface.nukkit.gac.GTAnticheat.<init>(GTAnticheat.kt:36) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_262]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_262]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_262]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_262]
at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_262]
at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:59) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:122) [server.jar:?]
at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:308) [server.jar:?]
at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:159) [server.jar:?]
at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:151) [server.jar:?]
at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:147) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:679) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:192) [server.jar:?]
06:31:17 [FATAL] Could not load plugin "GAC"

**Comment by GoodLucky777** [comment]
I think it is duplicated with #937

**Comment by tuilakhanh** [comment]
Use another anticheat plugin.
I think the GAC is very buggy now.

**Comment by joserobjr** [comment]
Thank you for the report!

It is indeed duplicated of #937 and I already found a solution, I'm going to post it there.
